Repository datahub-project/datahub, pull requests merged in 2022-07, with the labels that each got.

#5333 feat(ingest): lookml - adding support for only emitting reachable vie…
  metadata-ingestion/src/datahub/ingestion/source/looker.py
  metadata-ingestion/src/datahub/ingestion/source/looker_common.py
  metadata-ingestion/src/datahub/ingestion/source/lookml.py
  metadata-ingestion/tests/integration/lookml/lkml_samples/data.model.lkml
  metadata-ingestion/tests/integration/lookml/lkml_samples/data2.model.lkml
  metadata-ingestion/tests/integration/lookml/lkml_samples/foo2.view.lkml
  metadata-ingestion/tests/integration/lookml/lookml_reachable_views.json
  metadata-ingestion/tests/integration/lookml/test_lookml.py
  metadata-ingestion/tests/test_helpers/mce_helpers.py
Labels: ingestion

#5337 fix(siblings) Combine siblings data but remove duplicate data
  datahub-web-react/src/app/entity/shared/siblingUtils.ts
Labels: ui

#5316 fix(me) Cache the me query for performance reasons
  datahub-web-react/src/Mocks.tsx
  datahub-web-react/src/app/useGetAuthenticatedUser.tsx
Labels: performance

#5329 feat(bigquery): support size, rowcount, lastmodified based table selection for profiling
  metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py
  metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
  metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py
  metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
Labels: ingestion

#5346 feat(ingest): update CSV source to support description and ownership type
  docs/how/updating-datahub.md
  metadata-ingestion/examples/demo_data/csv_enricher_demo_data.csv
  metadata-ingestion/examples/recipes/csv_enricher_to_datahub_rest.dhub.yml
  metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
  metadata-ingestion/src/datahub/ingestion/source_config/csv_enricher.py
  metadata-ingestion/tests/integration/csv-enricher/csv_enricher_golden.json
  metadata-ingestion/tests/integration/csv-enricher/csv_enricher_test_data.csv
  metadata-ingestion/tests/integration/csv-enricher/test_csv_enricher.py
  metadata-ingestion/tests/unit/test_csv_enricher_source.py
Labels: product

#5341 Fixed UI issue: Tags list going outside the container
  datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
Labels: ui, product

#5104 feat(ingest): add salesforce connector
  datahub-web-react/src/images/logo-salesforce.svg
  metadata-ingestion/docs/sources/salesforce/salesforce.md
  metadata-ingestion/docs/sources/salesforce/salesforce_recipe.yml
  metadata-ingestion/setup.py
  metadata-ingestion/src/datahub/ingestion/source/salesforce.py
  metadata-ingestion/tests/integration/salesforce/mock_files/account_custom_fields_soql_response.json
  metadata-ingestion/tests/integration/salesforce/mock_files/account_fields_soql_response.json
  metadata-ingestion/tests/integration/salesforce/mock_files/entity_definition_soql_response.json
  metadata-ingestion/tests/integration/salesforce/mock_files/property_custom_fields_soql_response.json
  metadata-ingestion/tests/integration/salesforce/mock_files/property_custom_object_soql_response.json
  metadata-ingestion/tests/integration/salesforce/mock_files/property_fields_soql_response.json
  metadata-ingestion/tests/integration/salesforce/mock_files/record_count_property_response.json
  metadata-ingestion/tests/integration/salesforce/mock_files/versions_response.json
  metadata-ingestion/tests/integration/salesforce/salesforce_mces_golden.json
  metadata-ingestion/tests/integration/salesforce/test_salesforce.py
  metadata-service/war/src/main/resources/boot/data_platforms.json
Labels: ingestion

#5348 feat(schema) Show last observed timestamp in the schema tab
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/SchemaMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/dataset/mappers/VersionedDatasetMapper.java
  datahub-graphql-core/src/main/resources/entity.graphql
  datahub-web-react/src/app/entity/dataset/profile/__tests__/schema/SchemaTimeStamps.test.tsx
  datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaHeader.tsx
  datahub-web-react/src/app/entity/dataset/profile/schema/components/SchemaTimeStamps.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTab.tsx
  datahub-web-react/src/graphql/versionedDataset.graphql
  metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java
  metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
  metadata-models/src/main/pegasus/com/linkedin/entity/EnvelopedAspect.pdl
  metadata-models/src/main/pegasus/com/linkedin/schema/SchemaMetadata.pdl
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesV2.snapshot.json
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesVersionedV2.snapshot.json
Labels: product

#5353 feat(quickstart): Adding env variables and cli options for customizing mapped ports in quickstart
  docker/docker-compose.override.yml
  docker/docker-compose.yml
  docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
  docker/quickstart/docker-compose.quickstart.yml
  docs/quickstart.md
  metadata-ingestion/setup.py
  metadata-ingestion/src/datahub/cli/docker.py
  metadata-ingestion/src/datahub/entrypoints.py
Labels: devops

#5255 feat(query) Add get_entity_v2 to python package
  metadata-ingestion/examples/library/dataset_query_entity_v2.py
  metadata-ingestion/src/datahub/ingestion/graph/client.py
Labels: accepted, ingestion, sdk

#5380 fix(users): fix to not get invite token unless the invite token modal is visible
  datahub-web-react/src/app/identity/user/ViewInviteTokenModal.tsx
Labels: product

#5334 Add Changes to support smoke test on Datahub deployed on kubernetes Cluster
  docker/elasticsearch-setup/create-indices.sh
  settings.gradle
  smoke-test/.gitignore
  smoke-test/build.gradle
  smoke-test/requirements.txt
  smoke-test/smoke.sh
  smoke-test/test_e2e.py
  smoke-test/test_rapid.py
  smoke-test/tests/assertions/assertions_test.py
  smoke-test/tests/cli/datahub_graph_test.py
  smoke-test/tests/conftest.py
  smoke-test/tests/cypress/integration_test.py
  smoke-test/tests/delete/delete_test.py
  smoke-test/tests/domains/domains_test.py
  smoke-test/tests/managed-ingestion/managed_ingestion_test.py
  smoke-test/tests/policies/test_policies.py
  smoke-test/tests/tags-and-terms/tags_and_terms_test.py
  smoke-test/tests/test_stateful_ingestion.py
  smoke-test/tests/tokens/revokable_access_token_test.py
  smoke-test/tests/utils.py
Labels: devops

#5114 fix(PlayCookie) PLAY_TOKEN cookie rejected because userprofile exceeds 4096 chars
  build.gradle
  datahub-frontend/app/auth/AuthModule.java
  datahub-frontend/conf/application.conf
  datahub-frontend/play.gradle
  docs/debugging.md
Labels: product

#5188 feat(dashboards): add datasets field to DashboardInfo aspect
  datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
  datahub-web-react/src/app/entity/shared/tabs/Entity/DashboardDatasetsTab.tsx
  datahub-web-react/src/graphql/dashboard.graphql
  metadata-ingestion/tests/integration/looker/expected_output.json
  metadata-ingestion/tests/integration/looker/golden_test_allow_ingest.json
  metadata-ingestion/tests/integration/looker/golden_test_ingest.json
  metadata-ingestion/tests/integration/looker/golden_test_ingest_joins.json
  metadata-ingestion/tests/integration/looker/golden_test_ingest_unaliased_joins.json
  metadata-ingestion/tests/integration/metabase/metabase_mces_golden.json
  metadata-ingestion/tests/integration/mode/mode_mces_golden.json
  metadata-ingestion/tests/integration/powerbi/golden_test_ingest.json
  metadata-ingestion/tests/integration/tableau/tableau_mces_golden.json
  metadata-ingestion/tests/unit/test_redash_source.py
  metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardInfo.pdl
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json
  metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
Labels: community-contribution, product, modeling

#5389 Added Cursor pointer to tags
  datahub-web-react/src/app/shared/tags/TagTermGroup.tsx
Labels: product

#5372 Adds support for Domains in CSV source
  metadata-ingestion/examples/demo_data/csv_enricher_demo_data.csv
  metadata-ingestion/src/datahub/ingestion/graph/client.py
  metadata-ingestion/src/datahub/ingestion/source/csv_enricher.py
  metadata-ingestion/tests/integration/csv-enricher/csv_enricher_golden.json
  metadata-ingestion/tests/integration/csv-enricher/csv_enricher_test_data.csv
  metadata-ingestion/tests/unit/test_csv_enricher_source.py
Labels: product

#5394 Update application.yml
  metadata-service/factories/src/main/resources/application.yml
Labels: community-contribution, devops

#5365 fix(tests): Removes duplicate policies tests & makes DataHub user configurable
  smoke-test/test_e2e.py
  smoke-test/tests/policies/test_policies.py
  smoke-test/tests/tokens/revokable_access_token_test.py
  smoke-test/tests/utils.py
Labels: product, devops

#5383 fix(ingest): ensure upgrade checks run async
  metadata-ingestion/setup.py
  metadata-ingestion/src/datahub/cli/ingest_cli.py
  metadata-ingestion/src/datahub/entrypoints.py
  metadata-ingestion/src/datahub/ingestion/run/pipeline.py
  metadata-ingestion/src/datahub/upgrade/upgrade.py
  metadata-ingestion/tests/integration/clickhouse/docker-compose.yml
  metadata-ingestion/tests/integration/kafka/docker-compose.yml
Labels: ingestion

#5427 fix(ui): add dataset qualifiedName parameter to lineage query
  datahub-web-react/src/graphql/lineage.graphql
Labels: community-contribution

#5407 docs(bigquery): add changelog and unittest for profiling limits
  docs/how/updating-datahub.md
  metadata-ingestion/src/datahub/ingestion/source/sql/bigquery.py
  metadata-ingestion/tests/unit/test_bigquery_source.py
Labels: ingestion

#5415 fix(siblings): fixing lineage fetching for siblings & sources
  datahub-web-react/src/graphql/lineage.graphql
  datahub-web-react/src/graphql/relationships.graphql
  smoke-test/tests/cypress/cypress/integration/siblings/siblings.js
Labels: product

#5398 fix(ingest/glue): handle error when generating s3 tags for virtual view tables
  metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
Labels: ingestion, community-contribution, on-deck

#5412 fix(bigquery-usage): fix dataset name for sharded table
  metadata-ingestion/src/datahub/ingestion/source/usage/bigquery_usage.py
  metadata-ingestion/tests/unit/test_bigquery_usage_source.py
Labels: ingestion

#5438 feat(ingestion) Add new endpoint to test an ingestion connection
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolver.java
  datahub-graphql-core/src/main/resources/ingestion.graphql
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/ingest/execution/CreateTestConnectionRequestResolverTest.java
Labels: product

#5451 feat(cli,build): remove deprecated variables GMS_HOST/_PORT
  docker/datahub-actions/env/docker.env
  docker/datahub-mae-consumer/env/docker-without-neo4j.env
  docker/datahub-mae-consumer/env/docker.env
  docker/datahub-mce-consumer/env/docker.env
  docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
  docker/quickstart/docker-compose-without-neo4j.quickstart.yml
  docker/quickstart/docker-compose.quickstart.yml
  docs/how/updating-datahub.md
  metadata-ingestion/src/datahub/cli/cli_utils.py
  metadata-ingestion/tests/unit/test_cli_utils.py
  metadata-service/factories/src/main/resources/application.yml
Labels: ingestion

#5454 fix(search): make filters by default an empty list if null
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchAcrossLineageResolver.java
Labels: product

#5449 fix(hive): add column comment as a column description
  metadata-ingestion/docs/sources/hive/hive_recipe.yml
  metadata-ingestion/src/datahub/ingestion/source/sql/hive.py
Labels: ingestion

#5455 fix(ingest): fix serialization of report to handle nesting
  metadata-ingestion/src/datahub/ingestion/api/report.py
  metadata-ingestion/tests/unit/test_capability_report.py
Labels: ingestion

#5423 fix(tableau): fix tableau db error, add more logs
  metadata-ingestion/src/datahub/ingestion/source/tableau.py
Labels: ingestion

#5473 feat(ui): Partial support for Chart usage
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/chart/ChartStatsSummaryResolver.java
  datahub-graphql-core/src/main/resources/entity.graphql
  datahub-web-react/src/app/entity/chart/ChartEntity.tsx
  datahub-web-react/src/app/entity/chart/preview/ChartPreview.tsx
  datahub-web-react/src/app/entity/chart/profile/stats/ChartStatsSummarySubHeader.tsx
  datahub-web-react/src/app/entity/chart/shared/ChartStatsSummary.tsx
  datahub-web-react/src/graphql/chart.graphql
  datahub-web-react/src/graphql/search.graphql
  metadata-models/src/main/pegasus/com/linkedin/chart/ChartUsageStatistics.pdl
  metadata-models/src/main/pegasus/com/linkedin/chart/ChartUserUsageCounts.pdl
  metadata-utils/src/main/java/com/linkedin/metadata/Constants.java
Labels: product

#5418 feat(quickstart): experimental support for backup restore for quickstart
  docker/mysql-setup/init.sql
  docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
  docs/how/backup-datahub.md
  docs/how/restore-indices.md
  docs/quickstart.md
  metadata-ingestion/setup.cfg
  metadata-ingestion/src/datahub/cli/docker.py
Labels: devops

#5414 feat(dbt): updating source lineage logic
  metadata-ingestion/src/datahub/ingestion/source/dbt.py
  metadata-ingestion/tests/integration/dbt/dbt_deleted_actor_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_with_filter_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
Labels: ingestion

#5479 docs: fix docsearch config
  docs-website/docusaurus.config.js
Labels: product

#5478 feat(delete): hard delete deletes soft deleted entities
  docs/how/updating-datahub.md
  metadata-ingestion/src/datahub/cli/delete_cli.py
Labels: ingestion

#5452 fix(build): intermittent failure in github actions
  .github/workflows/build-and-test.yml
  .github/workflows/check-datahub-jars.yml
  .github/workflows/docker-feast-source.yml
  .github/workflows/docker-ingestion.yml
  .github/workflows/docker-postgres-setup.yml
  .github/workflows/docker-unified.yml
  .github/workflows/metadata-ingestion.yml
  .github/workflows/metadata-io.yml
  .github/workflows/metadata-model.yml
  .github/workflows/publish-datahub-jars.yml
  .github/workflows/spark-smoke-test.yml
  docker/docker-compose-with-cassandra.yml
  docker/docker-compose-without-neo4j.yml
  docker/docker-compose.yml
  docker/quickstart/docker-compose-without-neo4j-m1.quickstart.yml
  docker/quickstart/docker-compose-without-neo4j.quickstart.yml
  docker/quickstart/docker-compose.quickstart.yml
Labels: devops

#5471 feat(model, ingest): add user email in dashboard user usage counts
  metadata-ingestion/src/datahub/ingestion/source/looker.py
  metadata-ingestion/tests/integration/looker/looker_mces_usage_history.json
  metadata-models/src/main/pegasus/com/linkedin/dashboard/DashboardUserUsageCounts.pdl
Labels: ingestion

#5472 feat(ingest): add support for capability report in snowflake test connection
  metadata-ingestion/src/datahub/ingestion/api/source.py
  metadata-ingestion/src/datahub/ingestion/source/sql/snowflake.py
  metadata-ingestion/src/datahub/ingestion/source_config/sql/snowflake.py
  metadata-ingestion/tests/unit/test_snowflake_source.py
Labels: ingestion

#5482 feat(build): automatically mark issues as stale to close inactive issues
  .github/workflows/close-stale-issues.yml
Labels: devops

#5379 fix(ingest): Fixing dbt trino datatypes
  metadata-ingestion/src/datahub/ingestion/source/dbt.py
  metadata-ingestion/src/datahub/ingestion/source/sql/sql_types.py
  metadata-ingestion/tests/integration/dbt/dbt_deleted_actor_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_enabled_with_schemas_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_enabled_without_schemas_with_filter_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_test_events_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_test_with_complex_owner_patterns_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_test_with_data_platform_instance_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_test_with_target_platform_instance_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_with_external_metadata_files_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_with_schemas_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_without_schemas_mces_golden.json
  metadata-ingestion/tests/integration/dbt/dbt_without_schemas_with_filter_mces_golden.json
  metadata-ingestion/tests/integration/dbt/test_dbt.py
Labels: ingestion, community-contribution, on-deck

#5488 feat(spark-lineage): Support ssl cert disable functionality
  metadata-integration/java/datahub-client/src/main/java/datahub/client/rest/RestEmitter.java
  metadata-integration/java/datahub-client/src/main/java/datahub/client/rest/RestEmitterConfig.java
  metadata-integration/java/datahub-client/src/test/java/datahub/client/rest/RestEmitterTest.java
  metadata-integration/java/spark-lineage/README.md
  metadata-integration/java/spark-lineage/src/main/java/datahub/spark/consumer/impl/McpEmitter.java
Labels: ingestion

#5501 docs(auth): fix link to point to new doc
  docs/how/add-user-data.md
Labels: docs

#5499 docs(updating-datahub): add note for breaking change in looker usage …
  docs/how/updating-datahub.md
Labels: ingestion

#5492 fix(ingest): cleanup unused flake8 noqa statements
  metadata-ingestion/src/datahub/ingestion/source/sql/oracle.py
  metadata-ingestion/src/datahub/ingestion/source/sql/redshift.py
  metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
  metadata-ingestion/src/datahub/ingestion/source/sql/trino.py
  metadata-ingestion/src/datahub/telemetry/stats.py
  metadata-ingestion/tests/integration/lookml/test_lookml.py
Labels: ingestion

#5494 refactor(ci): refactor Docker build-and-push workflows
  .github/actions/docker-custom-build-and-push/action.yml
  .github/workflows/docker-unified.yml
Labels: devops

#5485 feat(cli): delete - make delete easier to use
  docs/how/delete-metadata.md
  metadata-ingestion/src/datahub/cli/cli_utils.py
  metadata-ingestion/src/datahub/cli/delete_cli.py
Labels: devops

#5503 Home Page: Flickering Issue on search input field
  datahub-web-react/src/app/home/HomePageHeader.tsx
Labels: product

#5515 Search Page: Flickering Issue on search input field
  datahub-web-react/src/app/search/SearchablePage.tsx
Labels: product

#5487 Ingestion: Added form to Looker and Tableau
  datahub-web-react/src/app/ingest/source/builder/RecipeForm/FormField.tsx
  datahub-web-react/src/app/ingest/source/builder/RecipeForm/RecipeForm.tsx
  datahub-web-react/src/app/ingest/source/builder/RecipeForm/utils.tsx
  datahub-web-react/src/app/ingest/source/conf/looker/looker.ts
  datahub-web-react/src/app/ingest/source/conf/sources.tsx
  datahub-web-react/src/app/ingest/source/conf/tableau/tableau.ts
Labels: product

#5495 feat(identity): update azure and okta connectors to emit Origin aspects
  metadata-ingestion/src/datahub/ingestion/source/identity/azure_ad.py
  metadata-ingestion/src/datahub/ingestion/source/identity/okta.py
  metadata-ingestion/tests/integration/azure_ad/azure_ad_mces_golden_default_config.json
  metadata-ingestion/tests/integration/azure_ad/azure_ad_mces_golden_nested_groups.json
  metadata-ingestion/tests/integration/okta/okta_mces_golden_custom_user_name_regex.json
  metadata-ingestion/tests/integration/okta/okta_mces_golden_default_config.json
  metadata-ingestion/tests/integration/okta/okta_mces_golden_include_deprovisioned_suspended_users.json
Labels: ingestion

#5507 feat(ui): Adding Search Select feature(frontend only)
  datahub-web-react/src/app/entity/Entity.tsx
  datahub-web-react/src/app/entity/EntityRegistry.tsx
  datahub-web-react/src/app/entity/chart/ChartEntity.tsx
  datahub-web-react/src/app/entity/container/ContainerEntity.tsx
  datahub-web-react/src/app/entity/dashboard/DashboardEntity.tsx
  datahub-web-react/src/app/entity/dataFlow/DataFlowEntity.tsx
  datahub-web-react/src/app/entity/dataJob/DataJobEntity.tsx
  datahub-web-react/src/app/entity/dataset/DatasetEntity.tsx
  datahub-web-react/src/app/entity/domain/DomainEntity.tsx
  datahub-web-react/src/app/entity/glossaryNode/GlossaryNodeEntity.tsx
  datahub-web-react/src/app/entity/glossaryTerm/GlossaryTermEntity.tsx
  datahub-web-react/src/app/entity/group/Group.tsx
  datahub-web-react/src/app/entity/mlFeature/MLFeatureEntity.tsx
  datahub-web-react/src/app/entity/mlFeatureTable/MLFeatureTableEntity.tsx
  datahub-web-react/src/app/entity/mlModel/MLModelEntity.tsx
  datahub-web-react/src/app/entity/mlModelGroup/MLModelGroupEntity.tsx
  datahub-web-react/src/app/entity/mlPrimaryKey/MLPrimaryKeyEntity.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearch.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchHeader.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/EmbeddedListSearchResults.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/SearchActionMenu.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/SearchExtendedMenu.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/SearchSelect.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/SearchSelectActions.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/SearchSelectBar.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/SearchSelectModal.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/action/ActionDropdown.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/action/DeleteDropdown.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/action/DeprecationDropdown.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/action/DomainsDropdown.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/action/GlossaryTermsDropdown.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/action/OwnersDropdown.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/action/TagsDropdown.tsx
  datahub-web-react/src/app/entity/shared/components/styled/search/types.ts
  datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx
  datahub-web-react/src/app/entity/shared/containers/profile/header/EntityHeader.tsx
  datahub-web-react/src/app/entity/shared/entity/EntityActions.tsx
  datahub-web-react/src/app/entity/shared/types.ts
  datahub-web-react/src/app/entity/shared/utils.ts
  datahub-web-react/src/app/entity/tag/Tag.tsx
  datahub-web-react/src/app/entity/user/User.tsx
  datahub-web-react/src/app/recommendations/renderer/component/EntityNameList.tsx
  datahub-web-react/src/app/search/SearchPage.tsx
  datahub-web-react/src/app/search/SearchResultList.tsx
  datahub-web-react/src/app/search/SearchResults.tsx
Labels: product

#5509 test(ingest): limit GMS retries in test
  metadata-ingestion/src/datahub/emitter/rest_emitter.py
  metadata-ingestion/tests/conftest.py
Labels: ingestion

#5523 fix(ingest)- airflow: update subdag check for compatibility with older Airflow versions
  metadata-ingestion/src/datahub_provider/client/airflow_generator.py
Labels: ingestion, community-contribution
