Repository datahub-project/datahub, pull requests merged in 2025-07, with the labels that each got.

#13899 fix(openapi): fix example
  metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
Labels: devops, pending-submitter-merge

#13914 feat(ingest): add source aspect number in telemetry
  metadata-ingestion/src/datahub/ingestion/api/source.py
  metadata-ingestion/src/datahub/ingestion/run/pipeline.py
Labels: ingestion, pending-submitter-merge

#13910 chore: Fix typo
  docs/actions/concepts.md
Labels: docs, community-contribution, merge-pending-ci

#13908 docs(slack): add docs on slackbot permissions
  docs/managed-datahub/slack/saas-slack-app.md
Labels: docs, pending-submitter-merge

#13081 fix[AddDatasetOwnership]: update logic to manage case with same owner…
  metadata-ingestion/src/datahub/ingestion/transformer/add_dataset_ownership.py
  metadata-ingestion/tests/unit/test_transform_dataset.py
Labels: ingestion, community-contribution, needs-review

#13928 feat(auditEvents): add in top level delete policy event by default
  docs/actions/events/audit-events-search-guide.md
  metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
  metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceImplTest.java
  metadata-service/configuration/src/main/resources/application.yaml
  metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
  metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/event/DeletePolicyEvent.java
  metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/event/UsageEventResult.java
  smoke-test/tests/audit_events/audit_events_test.py
Labels: docs, product, devops, smoke_test, needs-review

#10871 fix(login): show login errors provided in response
  datahub-web-react/src/app/auth/LogIn.tsx
Labels: community-contribution, product, merge-pending-ci, datahub-community-champion

#13935 refactor(ingest): centralise subtype strings
  metadata-ingestion/examples/ai/dh_ai_client.py
  metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
  metadata-ingestion/src/datahub/ingestion/source/mock_data/datahub_mock_data.py
  metadata-ingestion/src/datahub/ingestion/source/slack/slack.py
  metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
Labels: ingestion, pending-submitter-merge

#13931 update hover color in selects
  datahub-web-react/src/alchemy-components/components/Select/utils.ts
Labels: product, pending-submitter-merge

#13939 fix(ingest): mypy lint python 3.8
  metadata-ingestion/src/datahub/ingestion/source/fivetran/fivetran.py
Labels: ingestion, pending-submitter-merge

#13943 fix(docs): hide unsupported assertion API feature docs
  docs/api/tutorials/assertions.md
Labels: docs, pending-submitter-merge

#13891 fix(ui): Fix non-functional page size in tags page
  datahub-web-react/src/app/tags/ManageTags.tsx
Labels: product, pending-submitter-merge

#13924 feat(docs): Instructions for bulk creation using new assertions SDK
  docs-website/sidebars.js
  docs/api/tutorials/sdk/bulk-assertions-sdk.md
Labels: docs, pending-submitter-merge

#13923 feat(graphql) Add GraphQL Objects, Type classes, and Mappers for Templates and Modules
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/Constants.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/UrnToEntityMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleParamsMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleType.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleTypeMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleVisibilityMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateSurfaceMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateType.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/template/PageTemplateVisibilityMapper.java
  datahub-graphql-core/src/main/resources/app.graphql
  datahub-graphql-core/src/main/resources/entity.graphql
  datahub-graphql-core/src/main/resources/module.graphql
  datahub-graphql-core/src/main/resources/template.graphql
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/module/PageModuleMapperTest.java
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/module/PageModuleTypeTest.java
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/template/PageTemplateMapperTest.java
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/template/PageTemplateTypeTest.java
  li-utils/src/main/java/com/linkedin/metadata/Constants.java
  metadata-models/src/main/pegasus/com/linkedin/template/DataHubPageTemplateProperties.pdl
Labels: product, pending-submitter-merge

#13947 fix(token-service): extend validation for actor
  metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/StatefulTokenService.java
  metadata-service/auth-impl/src/main/java/com/datahub/authentication/token/StatelessTokenService.java
  metadata-service/auth-impl/src/test/java/com/datahub/authentication/token/StatelessTokenServiceTest.java
  smoke-test/tests/tokens/session_access_token_test.py
Labels: devops, pending-submitter-merge

#13936 feat(customHomePage): add asset item component
  datahub-web-react/src/app/entityV2/shared/__tests__/utils.test.ts
  datahub-web-react/src/app/entityV2/shared/containers/profile/header/PlatformContent/PlatformContentContainer.tsx
  datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/LastIngested.tsx
  datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/shared/StatusSection.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/AssertionList/utils.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Documentation/components/SourceDescription.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Incident/utils.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/__tests__/utils.test.tsx
  datahub-web-react/src/app/entityV2/shared/utils.ts
  datahub-web-react/src/app/homeV2/reference/sections/assets/useGetAssetsYouOwn.tsx
  datahub-web-react/src/app/homepageV2/HomePageContent.tsx
  datahub-web-react/src/app/homepageV2/module/Module.tsx
  datahub-web-react/src/app/homepageV2/module/components/EmptyContent.tsx
  datahub-web-react/src/app/homepageV2/module/components/EntityItem.tsx
  datahub-web-react/src/app/homepageV2/module/components/LargeModule.tsx
  datahub-web-react/src/app/homepageV2/module/modules/YourAssetsModule.tsx
  datahub-web-react/src/app/previewV2/ContextPath.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/DisplayName.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/icon/DefaultEntityIcon.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/icon/PlatformIcon.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/icon/SingleEntityIcon.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/matches/Matches.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/matches/components/Match.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/matches/components/MoreMatches.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/subtitle/DefaultEntitySubtitle.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/subtitle/UserEntitySubtitle.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/subtitle/types.ts
  datahub-web-react/src/app/searchV2/autoCompleteV2/constants.ts
  datahub-web-react/src/app/searchV2/autoCompleteV2/types.ts
  datahub-web-react/src/app/searchV2/searchBarV2/hooks/useAutocompleteSuggestionsOptions.tsx
  datahub-web-react/src/app/searchV2/searchBarV2/hooks/useRecentlyViewedEntitiesOptions.tsx
Labels: product, pending-submitter-merge

#13925 feat(templates/modules) Ingest default page templates and modules
  metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml
  metadata-service/configuration/src/main/resources/bootstrap_mcps/page-modules.yaml
  metadata-service/configuration/src/main/resources/bootstrap_mcps/page-templates.yaml
  metadata-service/war/src/main/resources/boot/global_settings.json
Labels: devops, pending-submitter-merge

#13748 feat(ingest/kafka-connect): Add more connectors the regexp transformation support
  metadata-ingestion/src/datahub/ingestion/source/kafka_connect/sink_connectors.py
  metadata-ingestion/tests/unit/test_kafka_connect.py
Labels: ingestion, pending-submitter-merge

#13932 feat(docs): v0.3.12.2 release notes
  docs/managed-datahub/release-notes/v_0_3_12.md
Labels: docs, pending-submitter-merge

#13951 feat(cli): add kafka helper, improve restore indices helper
  docs/cli.md
  metadata-ingestion/src/datahub/cli/check_cli.py
  metadata-ingestion/src/datahub/ingestion/graph/client.py
Labels: ingestion, docs, pending-submitter-merge

#13945 fix(graph/client): use fixed GMS URL consistently
  metadata-ingestion/src/datahub/ingestion/graph/client.py
Labels: ingestion, pending-submitter-merge

#13949 fix(ui): reset page in embedded components
  datahub-web-react/src/app/entityV2/shared/components/styled/search/EmbeddedListSearchEmbed.tsx
Labels: product, pending-submitter-merge

#13564 fix(ui/navBar): Fix logic to display manage tags link
  datahub-web-react/src/alchemy-components/components/Modal/Modal.tsx
  datahub-web-react/src/app/homeV2/layout/navBarRedesign/NavSidebar.tsx
  datahub-web-react/src/app/shared/NoPageFound.tsx
  datahub-web-react/src/app/tags/CreateNewTagModal/CreateNewTagModal.tsx
  datahub-web-react/src/app/tags/CreateNewTagModal/TagDetailsSection.tsx
  datahub-web-react/src/app/tags/CreateNewTagModal/types.ts
  datahub-web-react/src/app/tags/ManageTag.tsx
  datahub-web-react/src/app/tags/ManageTags.tsx
  datahub-web-react/src/app/tags/TagsTable.tsx
  datahub-web-react/src/app/tags/TagsTableColumns.tsx
  smoke-test/tests/cypress/cypress/e2e/manage_tags/manage_tags.js
  smoke-test/tests/cypress/cypress/e2e/manage_tagsV2/helpers/dataset_helper.js
  smoke-test/tests/cypress/cypress/e2e/manage_tagsV2/helpers/tags_page_helper.js
  smoke-test/tests/cypress/cypress/e2e/manage_tagsV2/manage_tagsV2.js
Labels: product, smoke_test, pending-submitter-merge

#13959 docs(dbt): incremental-lineage
  metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
Labels: ingestion, needs-review

#13958 feat(actions): require pydantic v2
  datahub-actions/setup.py
  datahub-actions/src/datahub_actions/pipeline/pipeline.py
  datahub-actions/src/datahub_actions/plugin/action/execution/executor_action.py
  datahub-actions/src/datahub_actions/plugin/action/hello_world/hello_world.py
  datahub-actions/src/datahub_actions/plugin/action/metadata_change_sync/metadata_change_sync.py
  datahub-actions/src/datahub_actions/plugin/action/propagation/docs/propagation_action.py
  datahub-actions/src/datahub_actions/plugin/action/propagation/propagation_utils.py
  datahub-actions/src/datahub_actions/plugin/action/slack/slack.py
  datahub-actions/src/datahub_actions/plugin/action/snowflake/tag_propagator.py
  datahub-actions/src/datahub_actions/plugin/action/stats_util.py
  datahub-actions/src/datahub_actions/plugin/action/tag/tag_propagation_action.py
  datahub-actions/src/datahub_actions/plugin/action/teams/teams.py
  datahub-actions/src/datahub_actions/plugin/action/term/term_propagation_action.py
  datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_event_source.py
  datahub-actions/src/datahub_actions/plugin/source/acryl/datahub_cloud_events_consumer.py
  datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py
  datahub-actions/src/datahub_actions/plugin/transform/filter/filter_transformer.py
  docs/how/updating-datahub.md
Labels: docs, pending-submitter-merge

#13954 feat(ingest): add modifiers on capability on sources
  metadata-ingestion/build.gradle
  metadata-ingestion/scripts/capability_summary.py
  metadata-ingestion/scripts/docgen.py
  metadata-ingestion/scripts/docgen.sh
  metadata-ingestion/src/datahub/ingestion/api/decorators.py
  metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json
  metadata-ingestion/src/datahub/ingestion/source/aws/glue.py
  metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
  metadata-ingestion/src/datahub/ingestion/source/salesforce.py
  metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
  metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py
  metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
  metadata-ingestion/src/datahub/ingestion/source/sql/teradata.py
  metadata-ingestion/src/datahub/ingestion/source/sql/vertica.py
  metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py
Labels: ingestion, pending-submitter-merge

#13607 feat(ingest/athena): Iceberg partition columns extraction
  metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
  metadata-ingestion/src/datahub/ingestion/source/sql/athena_properties_extractor.py
  metadata-ingestion/tests/integration/athena/athena_mce_golden.json
  metadata-ingestion/tests/unit/test_athena_properties_extractor.py
  metadata-ingestion/tests/unit/test_athena_source.py
Labels: ingestion, pending-submitter-merge

#13890 feat(ingest/snowflake): support TLL for stored procs
  metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
  metadata-ingestion/src/datahub/ingestion/source/snowflake/stored_proc_lineage.py
  metadata-ingestion/tests/unit/snowflake/test_stored_proc_lineage.py
Labels: ingestion, pending-submitter-merge

#13983 chore: add claude configs
  .claude/settings.json
  .gitignore
  CLAUDE.MD
  CLAUDE.md
  metadata-ingestion/CLAUDE.md
Labels: ingestion, pending-submitter-merge

#13968 build(docker): use root as build context
  .dockerignore
  docker/datahub-frontend/Dockerfile
  docker/datahub-gms/Dockerfile
  docker/datahub-mae-consumer/Dockerfile
  docker/datahub-mce-consumer/Dockerfile
  docker/datahub-upgrade/Dockerfile
  gradle/docker/docker.gradle
Labels: devops, pending-submitter-merge

#13970 fix(kafka-connect): handle SQL Server 3-level topic patterns and add Debezium integration tests
  metadata-ingestion/src/datahub/ingestion/source/kafka_connect/source_connectors.py
  metadata-ingestion/tests/integration/kafka-connect/docker-compose.override.yml
  metadata-ingestion/tests/integration/kafka-connect/kafka_connect_debezium_postgres_mces_golden.json
  metadata-ingestion/tests/integration/kafka-connect/kafka_connect_debezium_postgres_to_file.yml
  metadata-ingestion/tests/integration/kafka-connect/kafka_connect_debezium_sqlserver_mces_golden.json
  metadata-ingestion/tests/integration/kafka-connect/kafka_connect_debezium_sqlserver_to_file.yml
  metadata-ingestion/tests/integration/kafka-connect/kafka_connect_to_file.yml
  metadata-ingestion/tests/integration/kafka-connect/setup/init-sqlserver.sh
  metadata-ingestion/tests/integration/kafka-connect/setup/sqlserver-setup.sql
  metadata-ingestion/tests/integration/kafka-connect/test_kafka_connect.py
Labels: ingestion, pending-submitter-merge

#13814 feat(applications): Manage applications screen
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/MeResolver.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/application/ApplicationAuthorizationUtils.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/settings/applications/UpdateApplicationsSettingsResolver.java
  datahub-graphql-core/src/main/resources/app.graphql
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/settings/applications/UpdateApplicationsSettingsResolverTest.java
  datahub-web-react/src/Mocks.tsx
  datahub-web-react/src/app/SearchRoutes.tsx
  datahub-web-react/src/app/applications/ApplicationsTable.tsx
  datahub-web-react/src/app/applications/ApplicationsTableColumns.tsx
  datahub-web-react/src/app/applications/CreateNewApplicationModal/ApplicationDetailsSection.tsx
  datahub-web-react/src/app/applications/CreateNewApplicationModal/CreateNewApplicationModal.tsx
  datahub-web-react/src/app/applications/EmptyApplications.tsx
  datahub-web-react/src/app/applications/ManageApplications.tsx
  datahub-web-react/src/app/entityV2/application/ApplicationEntity.tsx
  datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/Applications/SidebarApplicationSection.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/AccessManagement/__tests__/AccessManagement.test.ts
  datahub-web-react/src/app/homeV2/layout/navBarRedesign/NavSidebar.tsx
  datahub-web-react/src/app/settingsV2/Preferences.tsx
  datahub-web-react/src/conf/Global.ts
  datahub-web-react/src/graphql/app.graphql
  datahub-web-react/src/graphql/me.graphql
  metadata-models/src/main/pegasus/com/linkedin/settings/global/ApplicationsSettings.pdl
  metadata-models/src/main/pegasus/com/linkedin/settings/global/GlobalSettingsInfo.pdl
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/ApplicationConfig.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/VisualConfiguration.java
  metadata-service/configuration/src/main/resources/application.yaml
  smoke-test/tests/cypress/cypress/e2e/application/manage_applications.js
Labels: product, pending-submitter-merge

#13984 fix(mysql): modifies hashing and equals behavior for primary keys to match mysql behavior
  metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectDao.java
  metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectV2.java
  metadata-io/src/test/java/com/linkedin/metadata/entity/EbeanEntityServiceTest.java
Labels: product, merge-pending-ci

#13997 fix(ci): cassandra test stabilization
  metadata-io/src/test/java/com/linkedin/metadata/CassandraTestUtils.java
  metadata-io/src/test/java/com/linkedin/metadata/entity/cassandra/CassandraAspectMigrationsDaoTest.java
  metadata-io/src/test/java/com/linkedin/metadata/entity/cassandra/CassandraEntityServiceTest.java
  metadata-io/src/test/java/com/linkedin/metadata/timeline/cassandra/CassandraTimelineServiceTest.java
Labels: product, pending-submitter-merge

#13948 feat(template) Add upsertPageTemplate graphql endpoint + service
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngineArgs.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/template/UpsertPageTemplateResolver.java
  datahub-graphql-core/src/main/resources/template.graphql
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/template/UpsertPageTemplateResolverTest.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactory.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/template/PageTemplateServiceFactory.java
  metadata-service/services/src/main/java/com/linkedin/metadata/service/PageTemplateService.java
  metadata-service/services/src/test/java/com/linkedin/metadata/service/PageTemplateServiceTest.java
Labels: product, devops, needs-review

#13978 feat(home) Get correct home page template and render rows/modules
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/settings/homePage/GlobalHomePageSettingsResolver.java
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/settings/homePage/GlobalHomePageSettingsResolverTest.java
  datahub-web-react/src/app/AppProviders.tsx
  datahub-web-react/src/app/context/GlobalSettingsContext.tsx
  datahub-web-react/src/app/context/GlobalSettingsProvider.tsx
  datahub-web-react/src/app/homeV2/reference/sections/assets/useGetAssetsYouOwn.tsx
  datahub-web-react/src/app/homeV3/HomePageContent.tsx
  datahub-web-react/src/app/homeV3/module/Module.tsx
  datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx
  datahub-web-react/src/app/homeV3/module/components/ModuleContainer.tsx
  datahub-web-react/src/app/homeV3/module/types.ts
  datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
  datahub-web-react/src/graphql/app.graphql
  datahub-web-react/src/graphql/me.graphql
  datahub-web-react/src/graphql/template.graphql
Labels: product, pending-submitter-merge

#13640 feat(ui) Use new Tabs component on entity profile pages
  datahub-web-react/src/alchemy-components/components/Tabs/Tabs.tsx
  datahub-web-react/src/app/entity/application/ApplicationEntity.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Governance/GovernanceTab.tsx
  datahub-web-react/src/app/entityV2/application/ApplicationEntity.tsx
  datahub-web-react/src/app/entityV2/chart/ChartEntity.tsx
  datahub-web-react/src/app/entityV2/dashboard/DashboardEntity.tsx
  datahub-web-react/src/app/entityV2/dataFlow/DataFlowEntity.tsx
  datahub-web-react/src/app/entityV2/dataJob/DataJobEntity.tsx
  datahub-web-react/src/app/entityV2/dataProduct/DataProductEntity.tsx
  datahub-web-react/src/app/entityV2/dataset/DatasetEntity.tsx
  datahub-web-react/src/app/entityV2/dataset/constants.ts
  datahub-web-react/src/app/entityV2/dataset/profile/useGetColumnTabCount.ts
  datahub-web-react/src/app/entityV2/domain/DomainEntity.tsx
  datahub-web-react/src/app/entityV2/glossaryTerm/GlossaryTermEntity.tsx
  datahub-web-react/src/app/entityV2/glossaryTerm/profile/useGlossaryRelatedAssetsTabCount.ts
  datahub-web-react/src/app/entityV2/mlFeature/MLFeatureEntity.tsx
  datahub-web-react/src/app/entityV2/mlFeatureTable/profile/Sources.tsx
  datahub-web-react/src/app/entityV2/mlModel/MLModelEntity.tsx
  datahub-web-react/src/app/entityV2/shared/containers/profile/EntityProfile.tsx
  datahub-web-react/src/app/entityV2/shared/containers/profile/header/EntityTabs.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/AcrylValidationsTab.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Entity/ColumnTabNameHeader.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Entity/TabNameWithCount.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Entity/components/EntityList.tsx
  datahub-web-react/src/app/entityV2/shared/types.ts
  smoke-test/tests/cypress/cypress/e2e/glossaryV2/v2_glossaryTerm.js
Labels: product, pending-submitter-merge

#13980 feat(ui) Finalize Your Assets module on the frontend
  datahub-web-react/src/alchemy-components/components/Button/types.ts
  datahub-web-react/src/alchemy-components/components/Button/utils.ts
  datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx
  datahub-web-react/src/app/homeV3/module/components/__tests__/LargeModule.test.tsx
  datahub-web-react/src/app/homeV3/modules/YourAssetsModule.tsx
  datahub-web-react/src/app/homeV3/modules/__tests__/useSearchYourAssets.test.ts
  datahub-web-react/src/app/homeV3/modules/useSearchYourAssets.ts
Labels: product, pending-submitter-merge

#13976 chore(deps):fix CVE-2021-37136 (com.typesafe.play : shaded-asynchttpclient)
  build.gradle
  datahub-frontend/app/controllers/Application.java
  datahub-frontend/test/app/ApplicationTest.java
Labels: community-contribution, product, needs-review

#14008 fix(ingest): add required json as part of CLI
  metadata-ingestion/setup.py
Labels: ingestion, pending-submitter-merge

#14011 misc(metrics): fix legacy metrics cache & tests
  metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessorTest.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/entityregistry/ConfigEntityRegistryFactory.java
  metadata-service/factories/src/test/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactoryTest.java
  metadata-utils/src/main/java/com/linkedin/metadata/utils/metrics/MetricUtils.java
  metadata-utils/src/test/java/com/linkedin/metadata/utils/metrics/MetricUtilsTimerCacheTest.java
Labels: devops, pending-submitter-merge

#13994 feat(customHomePage): add skeleton for adding new modules to a template
  datahub-web-react/src/alchemy-components/components/Dropdown/Dropdown.stories.tsx
  datahub-web-react/src/alchemy-components/components/Dropdown/Dropdown.tsx
  datahub-web-react/src/alchemy-components/components/Dropdown/constants.ts
  datahub-web-react/src/alchemy-components/components/Dropdown/reset-dropdown-menu-styles.less
  datahub-web-react/src/alchemy-components/components/Dropdown/types.ts
  datahub-web-react/src/app/homeV3/HomePageContent.tsx
  datahub-web-react/src/app/homeV3/module/components/__tests__/LargeModule.test.tsx
  datahub-web-react/src/app/homeV3/modules/__tests__/utils.test.ts
  datahub-web-react/src/app/homeV3/modules/constants.ts
  datahub-web-react/src/app/homeV3/modules/hooks/useModulesAvailableToAdd.ts
  datahub-web-react/src/app/homeV3/modules/types.ts
  datahub-web-react/src/app/homeV3/modules/utils.ts
  datahub-web-react/src/app/homeV3/styledComponents.ts
  datahub-web-react/src/app/homeV3/template/Template.tsx
  datahub-web-react/src/app/homeV3/template/components/AddModuleButton.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/__tests__/useAddModuleMenu.test.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/components/GroupItem.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/components/MenuItem.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/components/ModuleMenuItem.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
  datahub-web-react/src/app/homeV3/template/types.ts
  datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
  datahub-web-react/src/graphql/template.graphql
Labels: pending-submitter-response, product

#14023 chore(capability): remove capability summary task from pre-commit
  .github/scripts/pre-commit-override.yaml
  .pre-commit-config.yaml
Labels: devops, needs-review

#14028 fix(snowflake): resolve table name collision between FileBackedList and StoredProcLineageTracker
  metadata-ingestion/src/datahub/ingestion/source/snowflake/stored_proc_lineage.py
Labels: ingestion, pending-submitter-merge

#14030 feat(ci): upgrade to Cypress 14.5.1 (#6204)
  smoke-test/tests/cypress/cypress/e2e/search/query_and_filter_search.js
  smoke-test/tests/cypress/package.json
  smoke-test/tests/cypress/yarn.lock
Labels: community-contribution, smoke_test, needs-review

#13974 feat(ingestion): bring back ingestionV2 changes to OSS
  datahub-web-react/src/app/analytics/event.ts
  datahub-web-react/src/app/ingest/source/executions/IngestionSourceExecutionList.tsx
  datahub-web-react/src/app/ingestV2/ManageIngestionPage.tsx
  datahub-web-react/src/app/ingestV2/executions/ExecutionsTab.tsx
  datahub-web-react/src/app/ingestV2/executions/components/EmptyState.tsx
  datahub-web-react/src/app/ingestV2/executions/components/ExecutionDetailsModal.tsx
  datahub-web-react/src/app/ingestV2/executions/components/ExecutionsTable.tsx
  datahub-web-react/src/app/ingestV2/executions/components/columns/ActionsColumn.tsx
  datahub-web-react/src/app/ingestV2/executions/components/columns/CancelExecutionConfirmation.tsx
  datahub-web-react/src/app/ingestV2/executions/components/columns/RollbackExecutionConfirmation.tsx
  datahub-web-react/src/app/ingestV2/executions/components/columns/SourceColumn.tsx
  datahub-web-react/src/app/ingestV2/executions/constants.ts
  datahub-web-react/src/app/ingestV2/executions/hooks/__tests__/useCancelExecution.test.ts
  datahub-web-react/src/app/ingestV2/executions/hooks/__tests__/useRefresh.test.ts
  datahub-web-react/src/app/ingestV2/executions/hooks/__tests__/useRollbackExecution.test.ts
  datahub-web-react/src/app/ingestV2/executions/hooks/useCancelExecution.ts
  datahub-web-react/src/app/ingestV2/executions/hooks/useRefresh.ts
  datahub-web-react/src/app/ingestV2/executions/hooks/useRollbackExecution.ts
  datahub-web-react/src/app/ingestV2/executions/types.ts
  datahub-web-react/src/app/ingestV2/executions/utils.ts
  datahub-web-react/src/app/ingestV2/shared/components/columns/BaseActionsColumn.tsx
  datahub-web-react/src/app/ingestV2/shared/components/columns/DateTimeColumn.tsx
  datahub-web-react/src/app/ingestV2/shared/components/columns/StatusColumn.tsx
  datahub-web-react/src/app/ingestV2/shared/hooks/__tests__/useRefreshInterval.test.ts
  datahub-web-react/src/app/ingestV2/shared/hooks/useRefreshInterval.ts
  datahub-web-react/src/app/ingestV2/source/IngestionSourceList.tsx
  datahub-web-react/src/app/ingestV2/source/IngestionSourceRefetcher.tsx
  datahub-web-react/src/app/ingestV2/source/IngestionSourceTable.tsx
  datahub-web-react/src/app/ingestV2/source/IngestionSourceTableColumns.tsx
  datahub-web-react/src/app/ingestV2/source/__tests__/cacheUtils.test.ts
  datahub-web-react/src/app/ingestV2/source/__tests__/tests_utils.test.tsx
  datahub-web-react/src/app/ingestV2/source/__tests__/usePollSource.test.ts
  datahub-web-react/src/app/ingestV2/source/builder/IngestionSourceBuilderModal.tsx
  datahub-web-react/src/app/ingestV2/source/builder/NameSourceStep.tsx
  datahub-web-react/src/app/ingestV2/source/builder/types.ts
  datahub-web-react/src/app/ingestV2/source/cacheUtils.ts
  datahub-web-react/src/app/ingestV2/source/usePollSource.ts
  datahub-web-react/src/app/ingestV2/source/utils.ts
  datahub-web-react/src/app/ingestV2/types.ts
  datahub-web-react/src/app/sharedV2/StopPropagationWrapper.tsx
  datahub-web-react/src/app/sharedV2/owners/OwnersSection.tsx
Labels: product, needs-review

#14039 feat(ingest): add subtype capability modifier
  metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json
  metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery.py
  metadata-ingestion/src/datahub/ingestion/source/gcs/gcs_source.py
  metadata-ingestion/src/datahub/ingestion/source/sigma/sigma.py
  metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
  metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
  metadata-ingestion/src/datahub/ingestion/source/unity/source.py
Labels: ingestion, pending-submitter-merge

#13915 feat(ingestion): Introduce query dedup strategy
  metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
  metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
  metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_v2.py
  metadata-ingestion/tests/unit/snowflake/test_snowflake_querylog_builder.py
Labels: ingestion, pending-submitter-merge

#14007 feat(ingest): warn of older cli versions automatically
  metadata-ingestion/src/datahub/cli/check_cli.py
  metadata-ingestion/src/datahub/cli/cli_utils.py
  metadata-ingestion/src/datahub/cli/delete_cli.py
  metadata-ingestion/src/datahub/cli/docker_cli.py
  metadata-ingestion/src/datahub/cli/exists_cli.py
  metadata-ingestion/src/datahub/cli/get_cli.py
  metadata-ingestion/src/datahub/cli/ingest_cli.py
  metadata-ingestion/src/datahub/cli/put_cli.py
  metadata-ingestion/src/datahub/cli/specific/assertions_cli.py
  metadata-ingestion/src/datahub/cli/specific/datacontract_cli.py
  metadata-ingestion/src/datahub/cli/specific/dataproduct_cli.py
  metadata-ingestion/src/datahub/cli/specific/dataset_cli.py
  metadata-ingestion/src/datahub/cli/specific/forms_cli.py
  metadata-ingestion/src/datahub/cli/specific/group_cli.py
  metadata-ingestion/src/datahub/cli/specific/structuredproperties_cli.py
  metadata-ingestion/src/datahub/cli/specific/user_cli.py
  metadata-ingestion/src/datahub/cli/state_cli.py
  metadata-ingestion/src/datahub/cli/timeline_cli.py
  metadata-ingestion/src/datahub/entrypoints.py
  metadata-ingestion/src/datahub/ingestion/run/pipeline.py
  metadata-ingestion/src/datahub/upgrade/upgrade.py
  metadata-ingestion/src/datahub/utilities/server_config_util.py
Labels: ingestion, pending-submitter-merge

#14047 fix(alchemy): fix typo
  datahub-web-react/src/alchemy-components/README.mdx
Labels: product, needs-review

#14036 fix(ingest/tableau): optimize tableau test performance
  metadata-ingestion/tests/integration/tableau/tableau_cll_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_extract_all_project_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_filtered_upstream_asset_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_hidden_asset_tags_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_ingest_hidden_worksheets_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_ingest_tags_disabled_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_multiple_sites_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_nested_project_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_no_hidden_assets_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_permission_ingestion_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_signout_timeout_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_site_name_pattern_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_sites_as_container_mces_golden.json
  metadata-ingestion/tests/integration/tableau/tableau_with_platform_instance_mces_golden.json
  metadata-ingestion/tests/integration/tableau/test_tableau_ingest.py
Labels: ingestion, pending-submitter-merge

#13967 fix(ingest/teradata): Teradata perf improvements
  metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py
  metadata-ingestion/src/datahub/ingestion/source/sql/teradata.py
  metadata-ingestion/tests/unit/test_teradata_integration.py
  metadata-ingestion/tests/unit/test_teradata_performance.py
  metadata-ingestion/tests/unit/test_teradata_source.py
Labels: ingestion, pending-submitter-merge

#12637 feat Add more granular USERS and GROUPS privileges
  metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
Labels: community-contribution, merge-pending-ci

#13987 feat(openapi): add generic entity api for v3 CRUD operations
  metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
  metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/controller/EntityController.java
  metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
  smoke-test/tests/openapi/v3/generic_entities.json
Labels: pending-submitter-response, community-contribution, devops

#14040 fix(ingest/dremio): add debug info on failed requests
  metadata-ingestion/src/datahub/ingestion/source/dremio/dremio_api.py
Labels: ingestion, pending-submitter-merge

#14054 chore(airflow): remove v1 airflow plugin
  docs/how/updating-datahub.md
  docs/lineage/airflow.md
  metadata-ingestion-modules/airflow-plugin/setup.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_airflow_compat.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_airflow_shims.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_config.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_datahub_listener_module.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/_extractors.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/client/airflow_generator.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_listener.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_plugin.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/datahub_plugin_v22.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/example_dags/generic_recipe_sample_dag.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/example_dags/lineage_backend_demo.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/example_dags/lineage_backend_taskflow_demo.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/example_dags/lineage_emission_dag.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/example_dags/mysql_sample_dag.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/example_dags/snowflake_sample_dag.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/lineage/__init__.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/lineage/_lineage_core.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/lineage/datahub.py
  metadata-ingestion-modules/airflow-plugin/src/datahub_airflow_plugin/operators/datahub.py
  metadata-ingestion-modules/airflow-plugin/tests/integration/dags/custom_operator_dag.py
  metadata-ingestion-modules/airflow-plugin/tests/integration/dags/datahub_emitter_operator_jinja_template_dag.py
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v1_basic_iolets.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v1_simple_dag.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_athena_operator_no_dag_listener.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_basic_iolets_no_dag_listener.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_custom_operator_dag_no_dag_listener.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_custom_operator_sql_parsing_no_dag_listener.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_datahub_emitter_operator_jinja_template_dag_no_dag_listener.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_simple_dag_no_dag_listener.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/goldens/v2_sqlite_operator_no_dag_listener.json
  metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py
  metadata-ingestion-modules/airflow-plugin/tests/unit/test_airflow.py
  metadata-ingestion-modules/airflow-plugin/tests/unit/test_packaging.py
  metadata-ingestion-modules/airflow-plugin/tests/utils.py
Labels: ingestion, docs, pending-submitter-merge

#14058 fix(ci): avoid concurrent action cache updates
  .github/workflows/docker-unified.yml
Labels: devops, needs-review

#14061 fix(metrics): fix metrics warning
  metadata-service/configuration/src/main/resources/application.yaml
  metadata-utils/src/main/java/com/linkedin/metadata/utils/metrics/MetricUtils.java
  metadata-utils/src/test/java/com/linkedin/metadata/utils/metrics/MetricUtilsTimerCacheTest.java
Labels: devops, pending-submitter-merge

#14064 fix(test): fix test conflicts in openapi
  smoke-test/tests/openapi/v3/entities.json
  smoke-test/tests/utilities/concurrent_openapi.py
Labels: smoke_test, pending-submitter-merge

#14010 feat(homepage): support rendering top domains module in the new home page
  datahub-web-react/src/app/homeV3/module/Module.tsx
  datahub-web-react/src/app/homeV3/module/components/EmptyContent.tsx
  datahub-web-react/src/app/homeV3/module/components/EntityItem.tsx
  datahub-web-react/src/app/homeV3/modules/domains/TopDomainsModule.tsx
  datahub-web-react/src/app/homeV3/modules/domains/__tests__/useDomainModuleUtils.test.tsx
  datahub-web-react/src/app/homeV3/modules/domains/useDomainModuleUtils.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/icon/DefaultEntityIcon.tsx
Labels: product, needs-review

#14027 fix(homepage): remove default subscription module and its type references
  datahub-graphql-core/src/main/resources/module.graphql
  metadata-models/src/main/pegasus/com/linkedin/module/DataHubPageModuleType.pdl
  metadata-service/configuration/src/main/resources/bootstrap_mcps.yaml
  metadata-service/configuration/src/main/resources/bootstrap_mcps/page-modules.yaml
  metadata-service/configuration/src/main/resources/bootstrap_mcps/page-templates.yaml
Labels: product, devops, needs-review

#14025 feat(customHomePage): adjust rows component and add wrapping
  datahub-web-react/src/app/homeV3/module/components/ModuleContainer.tsx
  datahub-web-react/src/app/homeV3/template/Template.tsx
  datahub-web-react/src/app/homeV3/template/components/AddModuleButton.tsx
  datahub-web-react/src/app/homeV3/template/types.ts
  datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
  datahub-web-react/src/app/homeV3/templateRow/__tests__/utils.test.ts
  datahub-web-react/src/app/homeV3/templateRow/types.ts
  datahub-web-react/src/app/homeV3/templateRow/utils.ts
  datahub-web-react/src/app/previewV2/EntityHeader.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/DisplayName.tsx
Labels: product, needs-review

#13995 Enable UI theme V2 by default
  metadata-service/configuration/src/main/resources/application.yaml
Labels: devops, pending-submitter-merge

#14068 docs: typos fixed
  docs/developers.md
  docs/troubleshooting/build.md
Labels: docs, community-contribution, needs-review

#14046 fix(ingest/mlflow): add missing container modifier
  metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json
  metadata-ingestion/src/datahub/ingestion/source/mlflow.py
Labels: ingestion, pending-submitter-merge

#14069 fix(ingest/tableau): add missing container capability
  metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json
  metadata-ingestion/src/datahub/ingestion/source/common/subtypes.py
  metadata-ingestion/src/datahub/ingestion/source/tableau/tableau.py
  metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_constant.py
Labels: ingestion, pending-submitter-merge

#14071 fix(ingest): better experimental contract
  metadata-ingestion/src/datahub/ingestion/autogenerated/lineage_helper.py
  metadata-ingestion/tests/unit/autogenerated/test_lineage_helper.py
Labels: ingestion, pending-submitter-merge

#14065 chore(deps): fix (org.pac4j:pac4j-oidc)
  build.gradle
Labels: community-contribution, merge-pending-ci

#14057 feat(search): custom search configuration for highlighting
  docs/how/search.md
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/ESSearchDAO.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/AutocompleteRequestHandler.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/BaseRequestHandler.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/CustomizedQueryHandler.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/HighlightConfigurationResult.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchFieldConfig.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchQueryBuilder.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/query/request/SearchRequestHandler.java
  metadata-io/src/test/java/com/linkedin/metadata/search/query/SearchDAOTestBase.java
  metadata-io/src/test/java/com/linkedin/metadata/search/query/request/AutocompleteRequestHandlerTest.java
  metadata-io/src/test/java/com/linkedin/metadata/search/query/request/CustomizedQueryHandlerTest.java
  metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchQueryBuilderTest.java
  metadata-io/src/test/java/com/linkedin/metadata/search/query/request/SearchRequestHandlerTest.java
  metadata-io/src/test/resources/search_config_fixture_test.yml
  metadata-jobs/mce-consumer-job/src/main/java/com/linkedin/metadata/restli/RestliServletConfig.java
  metadata-models/src/main/pegasus/com/linkedin/metadata/query/SearchFlags.pdl
  metadata-service/configuration/build.gradle
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/CustomConfiguration.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/custom/CustomSearchConfiguration.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/custom/FieldConfiguration.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/custom/HighlightFields.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/custom/SearchFields.java
  metadata-service/configuration/src/main/resources/application.yaml
  metadata-service/configuration/src/main/resources/search_config.yaml
  metadata-service/configuration/src/test/java/com/linkedin/metadata/config/search/custom/CustomSearchConfigurationTest.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchServiceFactory.java
  metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/operations/elastic/ElasticsearchController.java
  metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/operations/elastic/ElasticsearchControllerTest.java
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
  metadata-service/war/src/main/java/com/linkedin/gms/servlet/RestliServletConfig.java
Labels: docs, product, devops, pending-submitter-merge

#13833 docs(ui/lineageV3): Update lineage docs with new copy and screenshots; add data flow lineage doc
  datahub-web-react/src/app/onboarding/config/LineageGraphOnboardingConfig.tsx
  docs-website/sidebars.js
  docs-website/src/learn/business-metric.md
  docs-website/src/learn/data-freshness.md
  docs-website/src/learn/data-pipeline.md
  docs/act-on-metadata/impact-analysis.md
  docs/features/feature-guides/lineage.md
  metadata-ingestion/scripts/docgen.py
Labels: ingestion, docs, product, pending-submitter-merge

#13716 feat(frontend): upgrade to vite 6, use vite plugin-react-swc
  datahub-web-react/build.gradle
  datahub-web-react/package.json
  datahub-web-react/src/app/entityV2/dataset/profile/__tests__/Schema.test.tsx
  datahub-web-react/src/app/entityV2/dataset/profile/__tests__/SchemaDescriptionField.test.tsx
  datahub-web-react/src/app/entityV2/shared/__tests__/utils.test.ts
  datahub-web-react/src/app/entityV2/shared/containers/profile/__tests__/EntityProfile.test.tsx
  datahub-web-react/src/app/lineage/__tests__/LineageEdges.test.tsx
  datahub-web-react/src/vite-env.d.ts
  datahub-web-react/vite.config.ts
  datahub-web-react/yarn.lock
Labels: product, needs-review

#14079 fix(openapi): openapi 3.1.0 nullable refs to use oneOf(ref, null)
  metadata-service/openapi-servlet/src/main/java/io/datahubproject/openapi/v3/OpenAPIV3Generator.java
  metadata-service/openapi-servlet/src/test/java/io/datahubproject/openapi/v3/OpenAPIV3GeneratorTest.java
Labels: community-contribution, devops, merge-pending-ci

#14085 chore(kafka-setup): bump aws-msk-iam-auth
  docker/kafka-setup/Dockerfile
Labels: devops, pending-submitter-merge

#14091 fix(ci): image publish only for master branch push or release
  .github/workflows/docker-unified.yml
Labels: devops, pending-submitter-merge

#14089 fix(quickstart): update commit hash with resolved quickstart profile
  metadata-ingestion/src/datahub/cli/quickstart_versioning.py
  metadata-ingestion/tests/unit/cli/docker/test_quickstart_version_mapping.py
Labels: ingestion, pending-submitter-merge

#14076 fix(ui) Allow aggregation searches for enum filter types
  datahub-web-react/src/app/searchV2/filters/value/EnumValueMenu.tsx
  datahub-web-react/src/app/searchV2/filters/value/__tests__/utils.test.tsx
  datahub-web-react/src/app/searchV2/filters/value/utils.tsx
  metadata-service/configuration/src/main/resources/application.yaml
Labels: product, devops, pending-submitter-merge

#14095 refactor(queries): refactor query edges
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/BackfillBrowsePathsV2Config.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/BackfillDataProcessInstancesConfig.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/BackfillIngestionSourceInfoIndicesConfig.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/BackfillPolicyFieldsConfig.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/NonBlockingConfigs.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/SchemaFieldsConfig.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/entities/RemoveQueryEdges.java
  datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/system/entities/RemoveQueryEdgesTest.java
  metadata-io/src/main/java/com/linkedin/metadata/graph/elastic/ESGraphQueryDAO.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/update/ESWriteDAO.java
  metadata-io/src/test/java/com/linkedin/metadata/search/LineageServiceTestBase.java
  metadata-io/src/test/java/com/linkedin/metadata/search/SearchServiceTestBase.java
  metadata-io/src/test/java/com/linkedin/metadata/search/TestEntityTestBase.java
  metadata-io/src/test/java/com/linkedin/metadata/search/elasticsearch/WriteDAOElasticSearchTest.java
  metadata-io/src/test/java/com/linkedin/metadata/search/opensearch/WriteDAOOpenSearchTest.java
  metadata-io/src/test/java/com/linkedin/metadata/search/update/ESWriteDAOTest.java
  metadata-io/src/test/java/com/linkedin/metadata/search/update/WriteDAOTestBase.java
  metadata-io/src/test/java/io/datahubproject/test/fixtures/search/SampleDataFixtureConfiguration.java
  metadata-io/src/test/java/io/datahubproject/test/fixtures/search/SearchLineageFixtureConfiguration.java
  metadata-io/src/testFixtures/java/io/datahubproject/test/search/SearchTestUtils.java
  metadata-models/src/main/pegasus/com/linkedin/query/QuerySubject.pdl
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/BulkDeleteConfiguration.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/BulkProcessorConfiguration.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/search/ElasticSearchConfiguration.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/utils/ParseUtils.java
  metadata-service/configuration/src/main/resources/application.yaml
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/ElasticSearchGraphServiceFactory.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/ElasticSearchSystemMetadataServiceFactory.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/BaseElasticSearchComponentsFactory.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchServiceFactory.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/timeseries/ElasticSearchTimeseriesAspectServiceFactory.java
Labels: product, devops, pending-submitter-merge

#14098 fix(ingest/dbt): improve dbt-cloud error message
  metadata-ingestion/src/datahub/ingestion/api/source.py
  metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_cloud.py
Labels: ingestion, pending-submitter-merge

#14099 chore(setuptools): bump setuptools
  datahub-actions/pyproject.toml
  metadata-ingestion-modules/airflow-plugin/pyproject.toml
  metadata-ingestion-modules/dagster-plugin/pyproject.toml
  metadata-ingestion-modules/gx-plugin/pyproject.toml
  metadata-ingestion-modules/prefect-plugin/pyproject.toml
  metadata-ingestion/pyproject.toml
  metadata-service/iceberg-catalog/pyproject.toml
  smoke-test/pyproject.toml
Labels: ingestion, devops, smoke_test, pending-submitter-merge

#14083 fix(ingest/deltalake): pin upperbound for delta lake
  metadata-ingestion/setup.py
Labels: ingestion, pending-submitter-merge

#14104 fix(snowflake): correct additional_database_names OR logic in access_history filter
  metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_queries.py
  metadata-ingestion/tests/unit/snowflake/test_snowflake_queries.py
Labels: ingestion, pending-submitter-merge

#14080 feat(tableau): add support for Google BigQuery connection type in pla…
  metadata-ingestion/src/datahub/ingestion/source/tableau/tableau_common.py
Labels: ingestion, pending-submitter-merge

#14094 chore(deps): bump kafka in kafka-setup
  docker/kafka-setup/Dockerfile
Labels: devops, needs-review

#14000 feat(graphql) Add deletePageModule GraphQL resolver
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/module/DeletePageModuleResolver.java
  datahub-graphql-core/src/main/resources/module.graphql
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/module/DeletePageModuleResolverTest.java
  metadata-service/services/src/main/java/com/linkedin/metadata/service/PageModuleService.java
  metadata-service/services/src/test/java/com/linkedin/metadata/service/PageModuleServiceTest.java
Labels: product, devops, pending-submitter-merge

#14106 fix(ingestion/abs): updated deprecated azure sdk parameter to supported parameter and uri prefix support of https
  metadata-ingestion/src/datahub/ingestion/source/abs/source.py
  metadata-ingestion/src/datahub/ingestion/source/azure/azure_common.py
  metadata-ingestion/src/datahub/ingestion/source/data_lake_common/object_store.py
  metadata-ingestion/tests/unit/abs/test_abs_source.py
  metadata-ingestion/tests/unit/data_lake/test_object_store.py
Labels: ingestion, pending-submitter-merge

#14097 feat(logical): Add feature flag and models
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
  datahub-graphql-core/src/main/resources/app.graphql
  datahub-web-react/src/appConfigContext.tsx
  datahub-web-react/src/graphql/app.graphql
  metadata-models/src/main/pegasus/com/linkedin/logical/LogicalParent.pdl
  metadata-models/src/main/resources/entity-registry.yml
  metadata-service/configuration/src/main/java/com/linkedin/datahub/graphql/featureflags/FeatureFlags.java
  metadata-service/configuration/src/main/resources/application.yaml
Labels: product, devops, pending-submitter-merge

#14110 chore(deps): bump commons-beanutils
  docker/kafka-setup/Dockerfile
Labels: devops, needs-review

#14113 fix(spring): fix null custom search config
  metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/spring/MCLSpringCommonTestConfiguration.java
  metadata-service/configuration/src/test/java/com/linkedin/metadata/config/DataHubAppConfigurationTest.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchServiceFactory.java
  metadata-service/factories/src/test/java/com/linkedin/gms/factory/graphql/GraphQLEngineFactoryTest.java
  metadata-service/factories/src/test/java/com/linkedin/gms/factory/search/DisabledCustomSearchTest.java
Labels: devops, pending-submitter-merge

#14116 chore(deps): bump commons-beanutils - one more location
  docker/kafka-setup/Dockerfile
Labels: devops, pending-submitter-merge

#13396 feat(dbt/ingestion): add support for nested meta properties mapping
  metadata-ingestion/docs/sources/dbt/dbt.md
  metadata-ingestion/src/datahub/ingestion/source/dbt/dbt_common.py
  metadata-ingestion/tests/integration/dbt/dbt_test_column_meta_mapping_golden.json
  metadata-ingestion/tests/integration/dbt/sample_dbt_manifest_1.json
  metadata-ingestion/tests/integration/dbt/test_dbt.py
Labels: ingestion, community-contribution, merge-pending-ci

#11542 Update add-user-data.md
  docs/how/add-user-data.md
Labels: docs, community-contribution, merge-pending-ci

#14115 fix(ci): use depot runners when possible
  .github/workflows/airflow-plugin.yml
  .github/workflows/build-and-test.yml
  .github/workflows/dagster-plugin.yml
  .github/workflows/gx-plugin.yml
  .github/workflows/metadata-ingestion.yml
  .github/workflows/metadata-io.yml
  .github/workflows/prefect-plugin.yml
Labels: devops, pending-submitter-merge

#13601 feat(ingest): enable use_queries_v2 by default for snowflake/bigquery
  docs/how/updating-datahub.md
  metadata-ingestion/docs/sources/snowflake/snowflake_recipe.yml
  metadata-ingestion/src/datahub/ingestion/source/bigquery_v2/bigquery_config.py
  metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_config.py
  metadata-ingestion/tests/integration/bigquery_v2/test_bigquery.py
  metadata-ingestion/tests/integration/snowflake/test_snowflake.py
  metadata-ingestion/tests/integration/snowflake/test_snowflake_failures.py
  metadata-ingestion/tests/integration/snowflake/test_snowflake_stateful.py
  metadata-ingestion/tests/integration/snowflake/test_snowflake_tag.py
Labels: ingestion, pending-submitter-merge

#14112 fix(ingest/athena): Make Athena simple column v1 conversion optional
  metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
  metadata-ingestion/tests/integration/athena/athena_mce_golden.json
  metadata-ingestion/tests/unit/test_athena_source.py
Labels: ingestion, pending-submitter-merge

#14105 feat(mock-data): allow throwing uncaught exception, errors, warning
  metadata-ingestion/src/datahub/ingestion/source/mock_data/datahub_mock_data.py
  metadata-ingestion/tests/unit/mock_data/test_datahub_mock_data_report.py
Labels: ingestion, pending-submitter-merge

#14121 Enabling SSL for gms if the keystore and password is passed
  metadata-service/war/src/main/java/com/linkedin/gms/CommonApplicationConfig.java
  metadata-service/war/src/test/java/com/linkedin/gms/SpringTest.java
Labels: community-contribution, devops, merge-pending-ci

#14078 feat(ui) Add ability to edit global template on homepage
  .github/workflows/build-and-test.yml
  datahub-web-react/src/alchemy-components/components/ActionsBar/ActionsBar.stories.tsx
  datahub-web-react/src/alchemy-components/components/ActionsBar/ActionsBar.tsx
  datahub-web-react/src/alchemy-components/components/ActionsBar/index.ts
  datahub-web-react/src/alchemy-components/index.ts
  datahub-web-react/src/app/homeV3/EditDefaultTemplateBar.tsx
  datahub-web-react/src/app/homeV3/EditDefaultTemplateButton.tsx
  datahub-web-react/src/app/homeV3/HomePageContent.tsx
Labels: product, pending-submitter-merge

#14050 feat(homePage): add the ability to create asset collection module
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/module/UpsertPageModuleResolver.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/module/PageModuleParamsMapper.java
  datahub-graphql-core/src/main/resources/module.graphql
  datahub-web-react/src/alchemy-components/components/Checkbox/Checkbox.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Properties/useHydratedEntityMap.ts
  datahub-web-react/src/app/homeV3/context/PageTemplateContext.tsx
  datahub-web-react/src/app/homeV3/context/__tests__/PageTemplateContext.test.tsx
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleModalState.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useTemplateOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/useModuleModalState.ts
  datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts
  datahub-web-react/src/app/homeV3/context/hooks/useTemplateOperations.ts
  datahub-web-react/src/app/homeV3/context/types.ts
  datahub-web-react/src/app/homeV3/module/Module.tsx
  datahub-web-react/src/app/homeV3/module/components/EntityItem.tsx
  datahub-web-react/src/app/homeV3/module/components/ModuleMenu.tsx
  datahub-web-react/src/app/homeV3/module/components/__tests__/ModuleMenu.test.tsx
  datahub-web-react/src/app/homeV3/moduleModals/ModuleModalMapper.tsx
  datahub-web-react/src/app/homeV3/moduleModals/common/BaseModuleModal.tsx
  datahub-web-react/src/app/homeV3/moduleModals/common/ModuleDetailsForm.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/AssetCollectionModal.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/AssetCollectionModule.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/AssetFilters.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/AssetsSection.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/EmptySection.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/SelectAssetsSection.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/SelectedAssetsSection.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/__tests__/useGetAssetResults.test.ts
  datahub-web-react/src/app/homeV3/modules/assetCollection/types.ts
  datahub-web-react/src/app/homeV3/modules/assetCollection/useGetAssetResults.ts
  datahub-web-react/src/app/homeV3/modules/constants.ts
  datahub-web-react/src/app/homeV3/styledComponents.ts
  datahub-web-react/src/app/homeV3/template/Template.tsx
  datahub-web-react/src/app/homeV3/template/components/AddModuleButton.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/__tests__/useAddModuleMenu.test.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx
  datahub-web-react/src/app/searchV2/searchBarV2/components/Filters.tsx
  datahub-web-react/src/app/sharedV2/__tests__/useGetEntities.test.ts
  datahub-web-react/src/app/sharedV2/propagation/utils.ts
  datahub-web-react/src/app/sharedV2/useGetEntities.ts
  datahub-web-react/src/graphql/template.graphql
  metadata-models/src/main/pegasus/com/linkedin/module/AssetCollectionModuleParams.pdl
  metadata-models/src/main/pegasus/com/linkedin/module/DataHubPageModuleParams.pdl
Labels: product, needs-review

#14138 fix(ci): quickstart ci - additional tests
  .github/workflows/quickstart-test.yml
Labels: devops, pending-submitter-merge

#14101 docs(upgrade): Add instructions / user guide for upgrading from Core to Cloud
  docs-website/sidebars.js
  docs/managed-datahub/upgrade_core_to_cloud.md
Labels: docs, pending-submitter-merge

#14081 feat(permissions) Add platform privilege for editing global home page
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/authorization/AuthorizationUtils.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/module/UpsertPageModuleResolver.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/template/UpsertPageTemplateResolver.java
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/module/UpsertPageModuleResolverTest.java
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/resolvers/template/UpsertPageTemplateResolverTest.java
  metadata-service/services/src/main/java/com/linkedin/metadata/service/PageModuleService.java
  metadata-service/services/src/test/java/com/linkedin/metadata/service/PageModuleServiceTest.java
  metadata-service/war/src/main/resources/boot/policies.json
  metadata-utils/src/main/java/com/linkedin/metadata/authorization/PoliciesConfig.java
Labels: product, devops, pending-submitter-merge

#14142 feat(ui) Fix alignment of rows and columns on new home page
  datahub-web-react/src/app/homeV3/EditDefaultTemplateButton.tsx
  datahub-web-react/src/app/homeV3/announcements/Announcements.tsx
  datahub-web-react/src/app/homeV3/header/Header.tsx
  datahub-web-react/src/app/homeV3/styledComponents.ts
  datahub-web-react/src/app/homeV3/template/Template.tsx
  datahub-web-react/src/app/homeV3/template/components/NewRowDropZone.tsx
  datahub-web-react/src/app/homeV3/template/components/TemplateGrid.tsx
  datahub-web-react/src/app/homeV3/templateRow/components/RowLayout.tsx
  datahub-web-react/src/app/sharedV2/__tests__/useGetEntities.test.ts
  datahub-web-react/src/app/sharedV2/useGetEntities.ts
Labels: product, needs-review

#14148 fix(tests): disable auth for spark test via env var instead of env file
  docker/build.gradle
  metadata-integration/java/spark-lineage-legacy/spark-smoke-test/smoke-gms.env
Labels: devops, pending-submitter-merge

#14042 fix(ui): pass createdBy to highlight query column
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/common/mappers/QueryPropertiesMapper.java
  datahub-graphql-core/src/main/resources/entity.graphql
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/common/mappers/QueryPropertiesMapperTest.java
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Queries/queryColumns.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Queries/types.ts
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Queries/useQueryTableColumns.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Queries/utils/mapQuery.ts
  datahub-web-react/src/graphql/query.graphql
Labels: product, pending-submitter-merge

#14151 feat(ui/homepage): handle drag and drop with small modules
  datahub-web-react/src/app/homeV3/context/hooks/useDragAndDrop.ts
  datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx
  datahub-web-react/src/app/homeV3/module/components/SmallModule.tsx
  datahub-web-react/src/app/homeV3/modules/constants.ts
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
  datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
  datahub-web-react/src/app/homeV3/templateRow/components/ModuleDropZone.tsx
  datahub-web-react/src/app/homeV3/templateRow/components/RowLayout.tsx
  datahub-web-react/src/app/homeV3/templateRow/hooks/useTemplateRowLogic.ts
Labels: product, needs-review

#14154 feat(quickstart): bump default version to v1.2.0
  .github/workflows/quickstart-test.yml
  docker/quickstart/quickstart_version_mapping.yaml
Labels: devops, pending-submitter-merge

#14123 feat(ingestion): make REST emitter batch max payload size configurable
  docs/how/updating-datahub.md
  metadata-ingestion/src/datahub/emitter/rest_emitter.py
Labels: ingestion, pending-submitter-merge

#14149 v0.3.12.4-acryl release notes
  docs/managed-datahub/release-notes/v_0_3_12.md
Labels: docs, pending-submitter-merge

#14130 feat(sdk): add container filter to search sdk
  metadata-ingestion/src/datahub/sdk/search_filters.py
  metadata-ingestion/tests/unit/sdk_v2/test_search_client.py
Labels: ingestion, pending-submitter-merge

#14157 ci(cypress): resize observer fix (#6263)
  smoke-test/tests/cypress/cypress/e2e/lineageV2/v2_lineage_graph.js
  smoke-test/tests/cypress/cypress/e2e/siblings/siblings.js
  smoke-test/tests/cypress/cypress/e2e/siblingsV2/v2_siblings.js
  smoke-test/tests/cypress/cypress/e2e/viewV2/v2_view_select.js
  smoke-test/tests/cypress/cypress/e2e/views/view_select.js
  smoke-test/tests/cypress/cypress/support/commands.js
Labels: community-contribution, smoke_test, merge-pending-ci

#14172 fix(ui/ingest): change title
  datahub-web-react/src/app/ingestV2/executions/components/ExecutionDetailsModal.tsx
Labels: product, pending-submitter-merge

#14167 fix(ui/ingest): cleanup, exception handling
  datahub-web-react/src/app/ingestV2/executions/components/SummaryTab.tsx
  datahub-web-react/src/app/ingestV2/source/IngestedAssets.tsx
  datahub-web-react/src/app/ingestV2/source/utils.ts
Labels: product, pending-submitter-merge

#14156 feat(kafka-consumer): micrometer kafka consumer metrics
  docs/advanced/monitoring.md
  metadata-io/src/main/java/com/linkedin/metadata/system_telemetry/GraphQLTimingInstrumentation.java
  metadata-io/src/main/java/com/linkedin/metadata/trace/TraceServiceImpl.java
  metadata-io/src/test/java/com/linkedin/metadata/trace/TraceServiceImplTest.java
  metadata-jobs/common/src/main/java/com/linkedin/metadata/kafka/listener/AbstractKafkaListener.java
  metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/DataHubUsageEventsProcessor.java
  metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/listener/mcl/MCLKafkaListener.java
  metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/DataHubUsageEventsProcessorTest.java
  metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/listener/mcl/MCLKafkaListenerTest.java
  metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessor.java
  metadata-jobs/mce-consumer/src/main/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessor.java
  metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/MetadataChangeProposalsProcessorTest.java
  metadata-jobs/mce-consumer/src/test/java/com/linkedin/metadata/kafka/batch/BatchMetadataChangeProposalsProcessorTest.java
  metadata-jobs/pe-consumer/src/main/java/com/datahub/event/PlatformEventProcessor.java
  metadata-jobs/pe-consumer/src/test/java/com/datahub/event/PlatformEventProcessorTest.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/DataHubConfiguration.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/MetricsOptions.java
  metadata-service/configuration/src/main/java/com/linkedin/metadata/config/kafka/ConsumerConfiguration.java
  metadata-service/configuration/src/main/resources/application.yaml
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/system_telemetry/KafkaMetricsConfiguration.java
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/system_telemetry/RequestMetricsConfiguration.java
  metadata-service/factories/src/test/java/com/linkedin/gms/factory/system_telemetry/KafkaMetricsConfigurationTest.java
  metadata-service/factories/src/test/java/com/linkedin/gms/factory/system_telemetry/RequestMetricsConfigurationTest.java
  metadata-utils/src/main/java/com/linkedin/metadata/utils/metrics/MetricUtils.java
  metadata-utils/src/test/java/com/linkedin/metadata/utils/metrics/MetricUtilsTest.java
Labels: product, devops, pending-submitter-merge

#14159 feat(sdk): add data products to suggested entity type filters
  metadata-ingestion/src/datahub/sdk/search_filters.py
  metadata-ingestion/tests/unit/sdk/test_client.py
Labels: ingestion, pending-submitter-merge

#14177 feat(ui/homepage): handle adding module to a row with 3 modules already
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/moduleOperationsUtils.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/useDragAndDrop.ts
  datahub-web-react/src/app/homeV3/context/hooks/useTemplateOperations.ts
  datahub-web-react/src/app/homeV3/context/hooks/utils/moduleOperationsUtils.ts
  datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
Labels: product, needs-review

#14102 feat(postgres): add support for stored procedures in postgres.
  metadata-ingestion/src/datahub/ingestion/source/sql/postgres.py
  metadata-ingestion/tests/integration/postgres/postgres_all_db_mces_with_db_golden.json
  metadata-ingestion/tests/integration/postgres/postgres_mces_with_db_golden.json
  metadata-ingestion/tests/integration/postgres/setup/setup.sql
Labels: ingestion, community-contribution, merge-pending-ci

#14153 fix(ingestion/abs): align add_partition_columns_to_schema functionality with working s3/gcs functionality in abs connector
  metadata-ingestion/src/datahub/ingestion/source/abs/source.py
  metadata-ingestion/src/datahub/ingestion/source/data_lake_common/data_lake_utils.py
  metadata-ingestion/src/datahub/ingestion/source/s3/source.py
  metadata-ingestion/tests/unit/data_lake/test_data_lake_utils.py
Labels: ingestion, pending-submitter-merge

#13507 ER-Model-Relationship UI Changes
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/ermodelrelationship/mappers/ERModelRelationMapper.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/ermodelrelationship/mappers/ERModelRelationshipUpdateInputMapper.java
  datahub-graphql-core/src/main/resources/entity.graphql
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/ermodelrelationship/mappers/ERModelRelationMapperTest.java
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/types/ermodelrelationship/mappers/ERModelRelationshipUpdateInputMapperTest.java
  datahub-web-react/src/app/entity/ermodelrelationships/ERModelRelationshipEntity.tsx
  datahub-web-react/src/app/entity/ermodelrelationships/_tests_/ERModelRelationshipSidebarCardinality.test.tsx
  datahub-web-react/src/app/entity/ermodelrelationships/preview/ERModelRelationshipPreviewCard.tsx
  datahub-web-react/src/app/entity/ermodelrelationships/profile/sidebar/ERModelRelationshipSidebarCardinality.tsx
  datahub-web-react/src/app/entity/shared/components/styled/ERModelRelationship/CreateERModelRelationModal.less
  datahub-web-react/src/app/entity/shared/components/styled/ERModelRelationship/CreateERModelRelationModal.tsx
  datahub-web-react/src/app/entity/shared/components/styled/ERModelRelationship/ERModelRelationPreview.less
  datahub-web-react/src/app/entity/shared/components/styled/ERModelRelationship/ERModelRelationPreview.tsx
  datahub-web-react/src/app/entity/shared/components/styled/ERModelRelationship/ERModelRelationUtils.tsx
  datahub-web-react/src/app/entity/shared/components/styled/_tests_/ERModelRelationPreview.test.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Relationship/RelationshipsTab.tsx
  datahub-web-react/src/app/preview/ERModelSidebarPreviewCard.tsx
  datahub-web-react/src/app/preview/_tests_/ERModelSidebarPreviewCard.test.tsx
  datahub-web-react/src/graphql/fragments.graphql
Labels: community-contribution, product, merge-pending-ci

#14163 feat(ui) Add ability to add custom global widgets to templates
  datahub-web-react/src/app/homeV3/modules/constants.ts
  datahub-web-react/src/app/homeV3/modules/hooks/useModulesAvailableToAdd.ts
  datahub-web-react/src/app/homeV3/modules/types.ts
  datahub-web-react/src/app/homeV3/template/Template.tsx
  datahub-web-react/src/app/homeV3/template/components/AddModuleButton.tsx
  datahub-web-react/src/app/homeV3/template/components/TemplateGrid.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/__tests__/useAddModuleMenu.test.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/__tests__/utils.test.ts
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/utils.ts
  datahub-web-react/src/app/homeV3/templateRow/TemplateRow.tsx
  datahub-web-react/src/app/homeV3/templateRow/components/RowLayout.tsx
Labels: product, pending-submitter-merge

#14175 feat(ui) Create and replace when editing global modules on personal template
  datahub-web-react/src/app/homeV3/context/PageTemplateContext.tsx
  datahub-web-react/src/app/homeV3/context/__tests__/PageTemplateContext.test.tsx
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleModalState.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/useModuleModalState.ts
  datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts
  datahub-web-react/src/app/homeV3/context/types.ts
  datahub-web-react/src/app/homeV3/module/components/ModuleMenu.tsx
Labels: product, pending-submitter-merge

#14171 fix(ui/homepage): fix outdated template on the homepage
  datahub-web-react/src/app/AppProviders.tsx
  datahub-web-react/src/app/homeV3/HomePageContent.tsx
  datahub-web-react/src/app/homeV3/context/HomePageProvider.tsx
Labels: product, pending-submitter-merge

#14193 ci: update pr-labeler
  .github/workflows/pr-labeler.yml
Labels: devops, pending-submitter-merge

#14182 feat(homePage) Migrate existing home page links to modules on default template
  metadata-service/factories/src/main/java/com/linkedin/metadata/boot/factories/BootstrapManagerFactory.java
  metadata-service/factories/src/main/java/com/linkedin/metadata/boot/steps/MigrateHomePageLinksStep.java
  metadata-service/factories/src/test/java/com/linkedin/metadata/boot/steps/MigrateHomePageLinksStepTest.java
  metadata-service/factories/src/test/resources/test-entity-registry.yaml
Labels: devops, needs-review

#14162 feat(audit): increase auditability with new system metadata tracking
  datahub-graphql-core/src/test/java/com/linkedin/datahub/graphql/TestUtils.java
  docs/how/updating-datahub.md
  entity-registry/src/main/java/com/linkedin/metadata/utils/SystemMetadataUtils.java
  entity-registry/src/test/java/com/linkedin/metadata/utils/SystemMetadataUtilsTest.java
  metadata-integration/java/datahub-client/src/main/resources/MetadataChangeProposal.avsc
  metadata-integration/java/datahub-event/src/main/resources/MetadataChangeProposal.avsc
  metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/ChangeItemImpl.java
  metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/PatchItemImpl.java
  metadata-io/metadata-io-api/src/main/java/com/linkedin/metadata/entity/ebean/batch/ProposedItem.java
  metadata-io/src/main/java/com/linkedin/metadata/entity/EntityServiceImpl.java
  metadata-io/src/main/java/com/linkedin/metadata/entity/ebean/EbeanAspectV2.java
  metadata-io/src/main/java/com/linkedin/metadata/systemmetadata/ElasticSearchSystemMetadataService.java
  metadata-io/src/test/java/com/linkedin/metadata/AspectGenerationUtils.java
  metadata-io/src/test/java/com/linkedin/metadata/aspect/utils/DefaultAspectsUtilTest.java
  metadata-io/src/test/java/com/linkedin/metadata/entity/EntityServiceTest.java
  metadata-models/src/main/pegasus/com/linkedin/mxe/SystemMetadata.pdl
  metadata-service/openapi-servlet/models/src/main/java/io/datahubproject/openapi/v3/models/GenericEntityV3.java
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesV2.snapshot.json
  metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entitiesVersionedV2.snapshot.json
  smoke-test/tests/openapi/v3/entities.json
Labels: ingestion, docs, product, devops, smoke_test, pending-submitter-merge

#14053 fix(ui): remove box-shadow, margin, and collapse button on embedded sidebar
  datahub-web-react/src/app/entityV2/shared/containers/profile/sidebar/EntityProfileSidebar.tsx
Labels: product, pending-submitter-merge

#14192 docs(metadata test): clarify current state
  docs/tests/metadata-tests.md
Labels: docs, pending-submitter-merge

#14194 fix(customHomePage): fixes after design review of hierarchy view
  datahub-web-react/src/app/homeV3/moduleModals/common/BaseModuleModal.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/HierarchyViewModal.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/DepthMargin.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/TreeNodeRenderer.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/context/TreeViewContextProvider.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/types.ts
Labels: product, needs-review

#14196 docs(townhall): Update Town Hall details
  docs/townhalls.md
Labels: docs, community-contribution, merge-pending-ci

#14165 feat(ui) Implement deleting of page modules when necessary
  datahub-web-react/src/app/homeV3/context/PageTemplateContext.tsx
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts
  datahub-web-react/src/app/homeV3/context/types.ts
  datahub-web-react/src/app/homeV3/module/components/ModuleMenu.tsx
  datahub-web-react/src/app/homeV3/module/components/__tests__/ModuleMenu.test.tsx
  datahub-web-react/src/app/homeV3/modules/constants.ts
  datahub-web-react/src/graphql/template.graphql
  metadata-service/services/src/main/java/com/linkedin/metadata/service/PageModuleService.java
  metadata-service/services/src/test/java/com/linkedin/metadata/service/PageModuleServiceTest.java
Labels: product, devops, pending-submitter-merge

#14198 fix(ui) Add miscellaneous design fixes to new home page
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/GmsGraphQLEngine.java
  datahub-web-react/src/alchemy-components/components/Dropdown/reset-dropdown-menu-styles.less
  datahub-web-react/src/app/ProtectedRoutes.tsx
  datahub-web-react/src/app/homeV3/EditDefaultTemplateBar.tsx
  datahub-web-react/src/app/homeV3/context/HomePageProvider.tsx
  datahub-web-react/src/app/homeV3/context/PageTemplateContext.tsx
  datahub-web-react/src/app/homeV3/context/__tests__/PageTemplateContext.test.tsx
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useShowHomePageRedesign.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useTemplateState.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/useShowHomePageRedesign.ts
  datahub-web-react/src/app/homeV3/context/hooks/useTemplateState.ts
  datahub-web-react/src/app/homeV3/header/Header.tsx
  datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx
  datahub-web-react/src/app/homeV3/module/components/ModuleMenu.tsx
  datahub-web-react/src/app/homeV3/module/components/ModuleName.tsx
  datahub-web-react/src/app/homeV3/module/components/SmallModule.tsx
  datahub-web-react/src/app/homeV3/modules/__tests__/utils.test.ts
  datahub-web-react/src/app/homeV3/modules/documentation/DocumentationModule.tsx
  datahub-web-react/src/app/homeV3/modules/utils.ts
  datahub-web-react/src/app/homeV3/styledComponents.ts
  datahub-web-react/src/app/homeV3/template/components/AddModuleButton.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/__tests__/useAddModuleMenu.test.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/components/GroupItem.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/components/icon/DefaultEntityIcon.tsx
  metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserHomePageSettings.pdl
Labels: product, pending-submitter-merge

#14174 fix(cli): do not check for compatibility if cloud
  metadata-ingestion/src/datahub/upgrade/upgrade.py
Labels: ingestion, pending-submitter-merge

#14190 feat(ingest/sql-queries): integrate SQL parsing aggregator with enhanced features
  metadata-ingestion/src/datahub/ingestion/source/sql_queries.py
  metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
  metadata-ingestion/tests/integration/bigquery_v2/bigquery_lineage_usage_golden.json
  metadata-ingestion/tests/integration/sql-queries/expectations/datahub-expectations.json
  metadata-ingestion/tests/integration/sql-queries/golden/basic-with-schema-resolver.json
  metadata-ingestion/tests/integration/sql-queries/golden/basic.json
  metadata-ingestion/tests/integration/sql-queries/golden/explicit-lineage.json
  metadata-ingestion/tests/integration/sql-queries/golden/hex-origin.json
  metadata-ingestion/tests/integration/sql-queries/golden/query-deduplication.json
  metadata-ingestion/tests/integration/sql-queries/golden/session-temp-tables.json
  metadata-ingestion/tests/integration/sql-queries/input/basic.jsonl
  metadata-ingestion/tests/integration/sql-queries/input/explicit-lineage.jsonl
  metadata-ingestion/tests/integration/sql-queries/input/explicit-lineage.yml
  metadata-ingestion/tests/integration/sql-queries/input/hex-origin.jsonl
  metadata-ingestion/tests/integration/sql-queries/input/hex-origin.yml
  metadata-ingestion/tests/integration/sql-queries/input/query-deduplication.jsonl
  metadata-ingestion/tests/integration/sql-queries/input/query-deduplication.yml
  metadata-ingestion/tests/integration/sql-queries/input/session-temp-tables.jsonl
  metadata-ingestion/tests/integration/sql-queries/input/session-temp-tables.yml
  metadata-ingestion/tests/integration/sql-queries/test_sql_queries.py
Labels: ingestion, pending-submitter-merge

#14200 docs(airflow): add missing config docs
  docs/lineage/airflow.md
Labels: docs, pending-submitter-merge

#14203 fix(ingestion/databricks): Fix quoting of catalog/schema/table names for databricks
  metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py
  metadata-ingestion/src/datahub/ingestion/source/unity/proxy.py
Labels: ingestion, pending-submitter-merge

#14189 feat(customHomePage): add telemetry
  datahub-web-react/src/app/analytics/event.ts
  datahub-web-react/src/app/homeV3/EditDefaultTemplateBar.tsx
  datahub-web-react/src/app/homeV3/EditDefaultTemplateButton.tsx
  datahub-web-react/src/app/homeV3/announcements/Announcements.tsx
  datahub-web-react/src/app/homeV3/context/hooks/useModuleModalState.ts
  datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts
  datahub-web-react/src/app/homeV3/context/types.ts
  datahub-web-react/src/app/homeV3/module/components/EntityItem.tsx
  datahub-web-react/src/app/homeV3/module/components/LargeModule.tsx
  datahub-web-react/src/app/homeV3/modules/YourAssetsModule.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/AssetCollectionModule.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/SelectAssetsSection.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/SelectedAssetsSection.tsx
  datahub-web-react/src/app/homeV3/modules/assetCollection/dragAndDrop/DraggableEntityItem.tsx
  datahub-web-react/src/app/homeV3/modules/domains/TopDomainsModule.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/domains/DomainsTreeView.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/components/glossary/GlossaryTreeView.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/context/TreeViewContextProvider.tsx
  datahub-web-react/src/app/homeV3/modules/hierarchyViewModule/treeView/types.ts
  datahub-web-react/src/app/homeV3/modules/link/LinkModule.tsx
  datahub-web-react/src/app/searchV2/autoCompleteV2/AutoCompleteEntityItem.tsx
  metadata-service/services/src/main/java/com/linkedin/metadata/datahubusage/DataHubUsageEventType.java
Labels: product, devops, pending-submitter-merge

#14209 improvement(ui/homepage): miscellaneous design review updates for custom home page
  datahub-web-react/src/app/homeV3/module/components/ModuleMenu.tsx
  datahub-web-react/src/app/homeV3/module/components/__tests__/ModuleMenu.test.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/components/ModuleMenuItem.tsx
  datahub-web-react/src/app/homeV3/template/components/addModuleMenu/useAddModuleMenu.tsx
Labels: product, needs-review

#14202 feat(homepage): add reset to default template functionality and update home page settings option
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/MeResolver.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/settings/user/UpdateUserHomePageSettingsResolver.java
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/types/corpuser/mappers/CorpUserMapper.java
  datahub-graphql-core/src/main/resources/app.graphql
  datahub-graphql-core/src/main/resources/entity.graphql
  datahub-web-react/src/Mocks.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/AccessManagement/__tests__/AccessManagement.test.ts
  datahub-web-react/src/app/homeV3/EditDefaultTemplateButton.tsx
  datahub-web-react/src/app/homeV3/HomePageContent.tsx
  datahub-web-react/src/app/homeV3/context/PageTemplateContext.tsx
  datahub-web-react/src/app/homeV3/context/__tests__/PageTemplateContext.test.tsx
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useTemplateOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/useTemplateOperations.ts
  datahub-web-react/src/app/homeV3/context/types.ts
  datahub-web-react/src/app/homeV3/settings/EditDefaultTemplateBar.tsx
  datahub-web-react/src/app/homeV3/settings/EditHomePageSettingsButton.tsx
  datahub-web-react/src/app/sharedV2/modals/ConfirmationModal.tsx
  datahub-web-react/src/graphql/me.graphql
Labels: product, pending-submitter-merge

#14152 Adding support for domains when upserting datasets with the cli
  metadata-ingestion/src/datahub/api/entities/dataset/dataset.py
  metadata-ingestion/tests/unit/api/entities/dataset/__init__.py
  metadata-ingestion/tests/unit/api/entities/dataset/dataset.yml
  metadata-ingestion/tests/unit/api/entities/dataset/golden_dataset_out.json
  metadata-ingestion/tests/unit/api/entities/dataset/golden_dataset_out_upsert.json
  metadata-ingestion/tests/unit/api/entities/dataset/test_dataset.py
Labels: ingestion, community-contribution, merge-pending-ci

#14166 Added code to programmatically load GMS certs into frontend SSL truststore
  datahub-frontend/app/auth/AuthModule.java
  datahub-frontend/app/controllers/Application.java
  datahub-frontend/app/utils/ConfigUtil.java
  datahub-frontend/app/utils/CustomHttpClientFactory.java
  datahub-frontend/app/utils/TruststoreConfig.java
  datahub-frontend/conf/application.conf
  datahub-frontend/test/utils/CustomHttpClientFactoryTest.java
  metadata-service/configuration/src/main/resources/application.yaml
Labels: community-contribution, product, devops, needs-review

#14201 feat(sql-parsing-aggregator): add override_dialect for observed query
  metadata-ingestion/src/datahub/ingestion/source/sql_queries.py
  metadata-ingestion/src/datahub/sql_parsing/sql_parsing_aggregator.py
  metadata-ingestion/tests/unit/sql_parsing/test_sql_aggregator.py
Labels: ingestion, pending-submitter-merge

#14225 chore(deps): fix (com.typesafe.play:shaded-oauth)
  build.gradle
Labels: community-contribution, needs-review

#14088 chore(deps): fix (commons-beanutils:commons-beanutils)
  build.gradle
Labels: community-contribution, needs-review

#14199 feat(lineage): restrict the creation of finegrained lineage in graphstore
  metadata-io/src/main/java/com/linkedin/metadata/service/UpdateGraphIndicesService.java
  metadata-jobs/mae-consumer/src/test/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHookTest.java
  metadata-service/configuration/src/main/resources/application.yaml
  metadata-service/factories/src/main/java/com/linkedin/gms/factory/entity/update/indices/UpdateIndicesServiceFactory.java
Labels: community-contribution, product, devops, needs-review

#14212 fix(sdk): make Filter type parsing more permissive
  metadata-ingestion/src/datahub/sdk/search_filters.py
  metadata-ingestion/tests/unit/sdk_v2/test_search_client.py
Labels: ingestion, pending-submitter-merge

#14211 updated tabs to remove margin minor updates to quality tab
  datahub-web-react/src/alchemy-components/components/Tabs/Tabs.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Governance/GovernanceTab.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Governance/TestResults.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Governance/TestResultsSummary.tsx
  datahub-web-react/src/app/entityV2/dataset/DatasetEntity.tsx
  datahub-web-react/src/app/entityV2/shared/tabs/Dataset/Validations/AcrylValidationsTab.tsx
  datahub-web-react/src/app/homeV2/content/tabs/announcements/AnnouncementsTab.tsx
  datahub-web-react/src/app/homeV2/content/tabs/discovery/DiscoveryTab.tsx
Labels: product, pending-submitter-merge

#14205 fix(ingest/sql-queries): handle string timestamps and empty table names
  metadata-ingestion/src/datahub/ingestion/source/sql_queries.py
  metadata-ingestion/tests/integration/sql-queries/golden/explicit-lineage.json
  metadata-ingestion/tests/integration/sql-queries/input/explicit-lineage.jsonl
  metadata-ingestion/tests/unit/sql_queries/__init__.py
  metadata-ingestion/tests/unit/sql_queries/test_sql_queries.py
Labels: ingestion, pending-submitter-merge

#14223 fix(customHomePage): fix hierarchy view with empty condition in filter
  datahub-web-react/src/app/sharedV2/queryBuilder/builder/__tests__/utils.test.tsx
  datahub-web-react/src/app/sharedV2/queryBuilder/builder/utils.ts
Labels: product, needs-review

#14238 feat(docker-gradle): localstack debug
  docker/build.gradle
  docker/profiles/docker-compose.frontend.yml
  docker/profiles/docker-compose.gms.yml
  docker/profiles/docker-compose.prerequisites.yml
  docker/quickstart/docker-compose.quickstart-profile.yml
Labels: devops, pending-submitter-merge

#14230 fix(customHomePage): fix splitting a row below when editing global module
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useModuleOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/__tests__/useTemplateOperations.test.ts
  datahub-web-react/src/app/homeV3/context/hooks/useModuleOperations.ts
  datahub-web-react/src/app/homeV3/context/hooks/useTemplateOperations.ts
Labels: product, pending-submitter-merge

#14241 feat(lineage): add pdl annotations for upstreams
  datahub-upgrade/build.gradle
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/config/BackfillDatasetLineageIndexFieldsConfig.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/lineage/BackfillDatasetLineageIndexFields.java
  datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system/lineage/BackfillDatasetLineageIndexFieldsStep.java
  datahub-upgrade/src/test/java/com/linkedin/datahub/upgrade/system/lineage/BackfillDatasetLineageIndexFieldsTest.java
  metadata-models/src/main/pegasus/com/linkedin/dataset/FineGrainedLineage.pdl
  metadata-models/src/main/pegasus/com/linkedin/dataset/Upstream.pdl
  smoke-test/tests/search/__init__.py
  smoke-test/tests/search/test_lineage_search_index_fields.py
Labels: smoke_test, merge-pending-ci, pending-submitter-merge
